CONTRIBUTING.md
e2e/cases/alias/__snapshots__/index.test.ts.snap
e2e/scripts/shared.ts
package.json
packages/core/src/config.ts
packages/core/src/utils/syntax.ts
packages/core/tests/__snapshots__/config.test.ts.snap
packages/core/tests/config.test.ts
packages/core/tests/syntax.test.ts
pnpm-lock.yaml

- Adding `>=` to browserslist query(e.g. `Chrome 120.0.0` -> `Chrome >= 120.0.0`) as it's not valid before, we didn't notice that because SWC could accept that([playground](https://play.swc.rs/?version=1.7.4&code=H4sIAAAAAAAAA0vOSSwuVnBUqOZSUFBOUrBVMOSqBQCnW%2F80FAAAAA%3D%3D&config=H4sIAAAAAAAAA1WPSw6CMBCG95yimTUhbDTGO3gC46KpA5bQR2YKkZDe3YIWZNf5%2FsdM50IIQDvCVczpmYYgqcXACdxBvcgZFKdLVVc1PJIhlkugY7UHvCRG2uZEeLJBvhMBVEayIu0DlFnteJEa2TOuKH4V6J1jzMqPGW11M%2F13K2c8IfPRuFilbXs8Nm8HG%2FccVjF%2FcvK43sdn2E152VYMmm85GWjAIn4AzaQM5jABAAA%3D)), but the lightningcss tool in Rspack is using browserslist to resolve the query in advance and it will throw an error.
- Change the default `syntax` to not dead browsers last 1 version. However, this is not correct for all scenes. As the default `syntax` should …

fix: browserslist query and rspack target

---

packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/tsc.ts

feat: print DTS generation time

---

e2e/cases/alias/index.test.ts
e2e/cases/alias/rslib.config.ts
e2e/cases/autoExtension/index.test.ts
e2e/cases/autoExtension/type-commonjs/rslib.config.ts
e2e/cases/autoExtension/type-module/rslib.config.ts
e2e/cases/bundle-false/basic/rslib.config.ts
e2e/cases/bundle-false/index.test.ts
e2e/cases/cli/index.test.ts
e2e/cases/cli/rslib.config.ts
e2e/cases/define/index.test.ts
e2e/cases/define/rslib.config.ts
e2e/cases/dts/bundle-false/rslib.config.ts
e2e/cases/dts/index.test.ts
e2e/cases/externals/browser/index.test.ts
e2e/cases/externals/browser/rslib.config.ts
e2e/cases/externals/node/index.test.ts
e2e/cases/externals/node/rslib.config.ts
e2e/cases/syntax/config/index.test.ts
e2e/cases/syntax/config/rslib.config.ts
e2e/cases/syntax/default/index.test.ts
e2e/cases/syntax/default/rslib.config.ts
e2e/package.json
e2e/scripts/helper.ts
e2e/scripts/index.ts
e2e/scripts/main.ts
e2e/scripts/package.json
e2e/scripts/shared.ts
pnpm-lock.yaml

at present, e2e cases with `package.json` ignore the imports field and it is too inconvenient
https://github.com/web-infra-dev/rslib/blob/864c46eb3fd6edbc336e926a7a92aeb7511c2f99/e2e/cases/autoExtension/type-commonjs/rslib.config.ts#L5
so, we can align with rsbuild, use `@e2e/helper` package to solve this issue

chore(infra/e2e): @e2e/helper rather than #imports

---

e2e/cases/dts/bundle/rslib.config.ts
e2e/scripts/shared.ts

chore(infra/e2e): use package name rather than "../"
#59

chore(infra/e2e): use package name rather than "../"

---

packages/core/src/build.ts
packages/core/src/cli/commands.ts
packages/core/src/cli/prepare.ts
packages/core/src/config.ts
packages/core/src/index.ts
packages/core/src/utils/extension.ts
packages/core/src/utils/helper.ts
packages/core/src/utils/logger.ts
packages/core/tsconfig.json
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
packages/plugin-dts/tsconfig.json
scripts/tsconfig/base.json

Enable TypeScript isolatedDeclarations, this allows us to speed up DTS generation.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#using-isolateddeclarations

perf: enable TypeScript isolatedDeclarations

---

e2e/package.json
packages/core/package.json
packages/plugin-dts/package.json
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml

dtsPromise only need registered once and print log with environment info.
before:
after:

feat(plugin-dts): dtsPromise only registered when firstCompile and print log with environment info

---

e2e/cases/dts/__snapshots__/index.test.ts.snap
e2e/cases/dts/bundle-false/rslib.distpath.config.ts
e2e/cases/dts/bundle-false/rslib.false.config.ts
e2e/cases/dts/bundle/rslib.distpath.config.ts
e2e/cases/dts/bundle/rslib.false.config.ts
e2e/cases/dts/index.test.ts
e2e/scripts/shared.ts
scripts/dictionary.txt

add tests of dts: false and dts.distPath

test: add tests of dts: false and dts.distPath

---

e2e/cases/dts/bundle-false/abortOnError.config.ts
e2e/cases/dts/bundle-false/src-error/const.ts
e2e/cases/dts/bundle-false/src-error/index.ts
e2e/cases/dts/bundle-false/tsconfig-error.json
e2e/cases/dts/bundle/abortOnError.config.ts
e2e/cases/dts/bundle/src-error/const.ts
e2e/cases/dts/bundle/src-error/index.ts
e2e/cases/dts/bundle/tsconfig-error.json
e2e/cases/dts/index.test.ts
e2e/scripts/shared.ts
packages/core/src/config.ts
packages/core/src/types/config/index.ts
packages/plugin-dts/src/index.ts

support `dts.abortOnError` option to control whether to exit process when dts build error.

feat: support dts.abortOnError

---

e2e/cases/autoExtension/index.test.ts
e2e/cases/autoExtension/type-commonjs/autoExtension.false.config.ts
e2e/cases/autoExtension/type-module/autoExtension.false.config.ts
e2e/cases/autoExtension/type-module/rslib.config.ts
packages/core/src/config.ts

Enable `autoExtension` by default when build js.
- generate `.mjs` in build artifacts with esm format when type is `commonjs`
- generate .`cjs` in build artifacts with cjs format when type is `module`

feat: enable autoExtension by default

---

e2e/cases/dts/__snapshots__/index.test.ts.snap
e2e/cases/dts/bundle-false/autoExtension.config.ts
e2e/cases/dts/bundle-false/package.json
e2e/cases/dts/bundle/autoExtension.config.ts
e2e/cases/dts/index.test.ts
examples/express-plugin/rslib.config.ts
examples/react-component/rslib.config.ts
packages/core/src/config.ts
packages/plugin-dts/package.json
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml

Support DTS autoExtension
- `.d.ts` with esm format and `.d.cts` with cjs format when `type: module`
- `.d.ts` with cjs format and `.d.mts` with esm format when `type: commonjs`

feat: support DTS autoExtension

---

e2e/cases/dts/bundle/bundleName.config.ts
e2e/cases/dts/index.test.ts
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/utils.ts

support generate bundle DTS name according to entry name.

feat: support DTS bundle file name

---

.github/workflows/test-windows.yml
e2e/cases/alias/__snapshots__/index.test.ts.snap
e2e/cases/syntax/__snapshots__/index.test.ts.snap
e2e/package.json
e2e/setupVitestTests.ts
packages/core/tests/lcp.test.ts
pnpm-lock.yaml

1. add windows test yml
2. add path-serializer as vitest snapshot serializer

ci: add windows test

---

e2e/cases/dts/bundle-false/__fixtures__/tsconfig.json
e2e/cases/dts/bundle-false/abort-on-error/tsconfig.json
e2e/cases/dts/bundle/__fixtures__/tsconfig.json
e2e/cases/dts/bundle/abort-on-error/tsconfig.json
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts

no need to specify `rootDir` in `tsconfig.json`

fix: rootDir in bundle DTS

---

CONTRIBUTING.md
package.json
packages/core/src/index.ts
pnpm-lock.yaml

- bump @rspack/core to with `module-import` temp fallback implementation
- only export necessary stuff from library

chore: bump @rspack/core

---

e2e/cases/shims/esm/rslib.config.ts
e2e/cases/shims/esm/src/index.ts
e2e/cases/shims/index.test.ts
packages/core/src/config.ts
packages/core/src/index.ts
packages/core/src/types/index.ts
packages/core/tests/__snapshots__/config.test.ts.snap

- don't touch `import.meta.abc` in ESM
- add shims test

feat: preserve import.meta.url in ESM

---

packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts

Align the time log format with Rsbuild.
- before:
- after:

feat: align the time log format with Rsbuild

---

.github/workflows/test-ubuntu.yml
.github/workflows/test-windows.yml
e2e/cases/bundle-false/index.test.ts
e2e/cases/dts/__snapshots__/index.test.ts.snap
e2e/cases/dts/index.test.ts
e2e/scripts/helper.ts
e2e/scripts/shared.ts
packages/core/src/utils/helper.ts
packages/core/tests/lcp.test.ts
packages/plugin-dts/src/utils.ts

windows CI is currently failed, fix them
#61

fix: windows ci

---

e2e/README.md

chore: update tests coverage status

---

e2e/cases/bundle-false/index.test.ts
e2e/cases/bundle-false/relative-import/package.json
e2e/cases/bundle-false/relative-import/rslib.config.ts
e2e/cases/bundle-false/relative-import/src/bar.ts
e2e/cases/bundle-false/relative-import/src/index.ts
e2e/cases/bundle-false/relative-import/tsconfig.json
e2e/scripts/shared.ts
packages/core/src/config.ts
packages/core/src/utils/helper.ts
packages/core/tests/helper.test.ts
pnpm-lock.yaml

add js extension for relative import in bundleless mode

feat: add js extension for relative import in bundleless mode

---

e2e/package.json
examples/react-component/package.json
packages/core/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml

Starting from v1.0.1-beta.14, rsbuild will output the inspect configs to the `.rsbuild` directory when use `DEBUG=rsbuild` and support clean up `.rsbuild` directory  by default.
https://github.com/web-infra-dev/rsbuild/pull/3210

feat: bump rsbuild to support clean inspect configs

---

README.md

- unify badges color
- add layers image

docs(README): unify badges color

---

.changeset/gorgeous-pets-bathe.md
e2e/package.json
packages/core/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml

bump `@rsbuild/core` to `1.0.1-beta.16`
https://github.com/web-infra-dev/rsbuild/releases/tag/v1.0.1-beta.16
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-rc.0
closes: #111

chore: bump @rsbuild/core

---

e2e/cases/auto-external/index.test.ts
e2e/cases/auto-external/module-import-warn/package.json
e2e/cases/auto-external/module-import-warn/rslib.config.ts
e2e/cases/auto-external/module-import-warn/src/index.ts
e2e/cases/externals/index.test.ts
e2e/cases/externals/module-import-warn/rslib.config.ts
e2e/cases/externals/module-import-warn/src/index.ts
e2e/cases/externals/node/rslib.config.ts
e2e/cases/externals/node/src/index.ts
e2e/package.json
e2e/scripts/helper.ts
packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
pnpm-lock.yaml

When using `require` to load an external module in ESM output, the `require` statement will adopt the `module` external type (the behavior of `"module-import"` external type). However, it can be challenging to identify the desired external type for the `require` statement. As a result, a warning will prompt the user to explicitly specify the correct external type.

feat: add warn when request type bail from "module-import"

---

e2e/cases/extension-alias/__snapshots__/index.test.ts.snap
e2e/cases/extension-alias/index.test.ts
e2e/cases/extension-alias/package.json
e2e/cases/extension-alias/rslib.config.ts
e2e/cases/extension-alias/src/bar.js
e2e/cases/extension-alias/src/foo.ts
e2e/cases/extension-alias/src/index.ts
e2e/cases/extension-alias/tsconfig.json
packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
pnpm-lock.yaml
scripts/dictionary.txt

closes: #41 
We add builtin `resolve.extensionAlias` to align with the TypeScript specific behavior: if the extension is ".js" or ".jsx", try replacing it with ".ts" or ".tsx"
```ts
resolve: {
extensionAlias: {
'.js': ['.ts', '.tsx', '.js', '.jsx'],
'.jsx': ['.tsx', '.jsx'],
'.mjs': ['.mts', '.mjs'],
'.cjs': ['.cts', '.cjs'],
},
},
```

feat: support default extensionAlias

---

e2e/cases/bundle-false/basic/package.json
e2e/cases/bundle-false/index.test.ts
e2e/cases/bundle-false/single-file/package.json
e2e/cases/cli/package.json
e2e/cases/define/package.json
e2e/cases/dts/bundle-false/abort-on-error/package.json
e2e/cases/dts/bundle-false/basic/package.json
e2e/cases/dts/bundle-false/dist-path/package.json
e2e/cases/dts/bundle-false/false/package.json
e2e/cases/externals/browser/package.json
e2e/cases/externals/module-import-warn/package.json
e2e/cases/externals/node/package.json
e2e/cases/shims/esm/package.json
e2e/cases/syntax/config/package.json
e2e/cases/syntax/default/package.json
pnpm-lock.yaml

add `package.json` for all tests, `autoExtension` and `autoExternal` should work correctly when running all tests.

chore: add package.json for tests

---

e2e/cases/bundle-false/index.test.ts
e2e/cases/bundle-false/relative-import/src/baz.js.ts
e2e/cases/bundle-false/relative-import/src/foo.js
e2e/cases/bundle-false/relative-import/src/index.ts
e2e/cases/bundle-false/relative-import/src/qux.cjs
packages/core/src/config.ts

fix: add extension when relative import already have an extension

---

package.json
pnpm-lock.yaml
scripts/tsconfig/base.json
scripts/tsconfig/package.json

- upgrade pnpm to `9.9.0`
- remove `@tsconfig/strictest` and explicitly declare tsconfig to avoid some bugs from resolver

chore: explicit tsconfig.json

---

packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
packages/core/tests/config.test.ts

The priorities from high to low are as follows:
1. `userConfig`: users can configure any Rsbuild and Rspack config
2. `libRsbuildConfig`: the configuration that we compose from Rslib unique config and userConfig from 1
3. `internalRsbuildConfig`: the built-in best practice Rsbuild configuration we provide in Rslib
We should state in the document that the built-in configuration should not be changed optionally

feat: modify merge config order

---

e2e/cases/externals/index.test.ts
e2e/cases/externals/module-import-warn/rslib.config.ts
e2e/cases/externals/module-import-warn/src/baz.ts
e2e/cases/externals/module-import-warn/src/index.ts
packages/core/src/config.ts
scripts/dictionary.txt

fix: warn should handles all externals config

---

e2e/cases/syntax/__snapshots__/index.test.ts.snap
e2e/cases/syntax/config/rslib.config.ts
e2e/cases/syntax/index.test.ts
packages/core/src/config.ts
packages/core/src/utils/syntax.ts
packages/core/tests/syntax.test.ts

In the past, for syntax, `[es5]` and `es5` were different, the former would be treated as browserslist processing while the latter is a valid esX version. This PR has removed this restriction, now `[es5]` and `es5` are equivalent, and esX can participate in the target syntax grammar, such as `['es2015', 'Chrome 123']`. Array-form syntax now is the superset of browserslist.

fix: syntax could handle combined pattern

---

e2e/cases/syntax/config/rslib.config.ts
packages/core/rslib.config.ts
packages/core/src/config.ts
packages/core/src/types/config/index.ts
packages/core/tests/config.test.ts

We try to flatten the fields under `lib` as much as possible instead of nesting them.

feat!: move config `output.syntax` to `syntax`

---

e2e/cases/external-helpers/__fixtures__/src/index.ts
e2e/cases/external-helpers/__fixtures__/tsconfig.json
e2e/cases/external-helpers/__snapshots__/index.test.ts.snap
e2e/cases/external-helpers/config-override/package.json
e2e/cases/external-helpers/config-override/rslib.config.ts
e2e/cases/external-helpers/default/package.json
e2e/cases/external-helpers/default/rslib.config.ts
e2e/cases/external-helpers/index.test.ts
e2e/cases/external-helpers/no-deps/package.json
e2e/cases/external-helpers/no-deps/rslib.config.ts
e2e/cases/external-helpers/true/package.json
e2e/cases/external-helpers/true/rslib.config.ts
e2e/cases/syntax/__snapshots__/index.test.ts.snap
packages/core/src/config.ts
packages/core/src/constant.ts
packages/core/src/types/config/index.ts
packages/core/tests/__snapshots__/config.test.ts.snap
pnpm-lock.yaml

support `externalHelpers` config to control whether to externalize `@swc/helpers`, default is false in Rslib, this is different from Rsbuild's default value.

feat: support `externalHelpers`

---

packages/core/src/config.ts
packages/core/src/utils/helper.ts

`omitDeep` will break some element like 
```TS
tools: {
rspack: {
plugins: [
new rspack.BannerPlugin({
banner: 'hello world',
footer: true,
stage: 10000,
}),
],
},
},
```

chore: not use recursive omit

---

e2e/cases/auto-external/index.test.ts
e2e/cases/define/index.test.ts
e2e/cases/define/rslib.config.ts
e2e/cases/define/src/index.ts
e2e/scripts/shared.ts
packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap

https://webpack.js.org/configuration/optimization/#optimizationnodeenv.
Previously, it will be `"production"` that uses `mode` by default. We usually leave this as-is in library and replace it by app.

fix: should remain process.env.NODE_ENV as is by default

---

.changeset/nice-hotels-cheer.md
e2e/cases/banner-footer/index.test.ts
e2e/cases/banner-footer/package.json
e2e/cases/banner-footer/rslib.config.ts
e2e/cases/banner-footer/src/foo.ts
e2e/cases/banner-footer/src/index.css
e2e/cases/banner-footer/src/index.ts
e2e/cases/banner-footer/tsconfig.json
e2e/cases/extension-alias/rslib.config.ts
e2e/scripts/shared.ts
packages/core/src/config.ts
packages/core/src/types/config/index.ts
packages/core/src/utils/helper.ts
packages/plugin-dts/package.json
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml

This PR implements the `banner` and `footer` feature.
We use [bannerPlugin](https://rspack.dev/zh/plugins/webpack/banner-plugin#bannerplugin) of Rspack to add banner and footer in js/css build. 
Notice: 
1. only `string` type is supported and will not be wrapped in a comment. 
2. The default stage is `PROCESS_ASSETS_STAGE_OPTIMIZE_SIZE + 1` to prevent avoid influence of minimizers
3. If you have further demand on banner and footer, you can directly use [bannerPlugin](https://rspack.dev/zh/plugins/webpack/banner-plugin#bannerplugin).
```ts
type BannerAndFooter = {
js?: string;
css?: string;
dts?: string;
};
interface LibConfig extends RsbuildConfig {
banner?: BannerAndFooter;
footer?: BannerAndFooter;
}
```
Since support of css of bundleless mode is not ready, we ignore css banner and …

feat: support `banner` and `footer`

---

e2e/README.md
e2e/cases/sourcemap/__fixtures__/src/index.ts
e2e/cases/sourcemap/__fixtures__/tsconfig.json
e2e/cases/sourcemap/default/package.json
e2e/cases/sourcemap/default/rslib.config.ts
e2e/cases/sourcemap/external/package.json
e2e/cases/sourcemap/external/rslib.config.ts
e2e/cases/sourcemap/index.test.ts
e2e/cases/sourcemap/inline/package.json
e2e/cases/sourcemap/inline/rslib.config.ts
e2e/scripts/shared.ts
pnpm-lock.yaml

test: add sourcemap tests

---

e2e/README.md
e2e/cases/decorators/__fixtures__/src/index.ts
e2e/cases/decorators/__fixtures__/tsconfig.decorators.json
e2e/cases/decorators/__fixtures__/tsconfig.json
e2e/cases/decorators/__snapshots__/index.test.ts.snap
e2e/cases/decorators/default/package.json
e2e/cases/decorators/default/rslib.config.ts
e2e/cases/decorators/index.test.ts
e2e/cases/decorators/tsconfig/package.json
e2e/cases/decorators/tsconfig/rslib.config.ts
e2e/cases/tsconfig/index.test.ts
e2e/cases/tsconfig/package.json
e2e/cases/tsconfig/rslib.config.ts
e2e/cases/tsconfig/src/foo.ts
e2e/cases/tsconfig/src/index.ts
e2e/cases/tsconfig/tsconfig.custom.json
packages/core/package.json
packages/core/prebundle.config.mjs
packages/core/rslib.config.ts
packages/core/src/config.ts
packages/core/src/utils/tsconfig.ts
packages/core/tests/extension.test.ts
packages/core/tests/fixtures/tsconfig/exist/tsconfig.custom.json
packages/core/tests/fixtures/tsconfig/exist/tsconfig.json
packages/core/tests/fixtures/tsconfig/no-exist/index.js
packages/core/tests/tsconfig.test.ts
packages/core/tsconfig.json
pnpm-lock.yaml
scripts/dictionary.txt

- use tsconfck to find and parse tsconfig file
- set legacy decorators version when `experimentalDecorators` enabled
- add `tsconfigPath` test cases
- prebundle `rslog`

feat: set legacy decorators version when `experimentalDecorators` enabled

---

packages/core/src/config.ts
packages/core/src/types/config/index.ts
packages/core/src/utils/syntax.ts
packages/core/tests/syntax.test.ts

Previously, there was no corresponding browserslist for esnext and es2024. It is difficult to convert esnext to the corresponding browserslist, so take the latest version of node or browser based on the target as the esnext browserslist.

fix: should resolve esnext browserslist

---

netlify.toml

Don't create preview documents for every pull request, it's noisy and wastes resources. Only trigger them when the documentation is relevant.
https://docs.netlify.com/configure-builds/ignore-builds/#mimic-default-behavior:~:text=The%20following%20ignore%20command%20example%20adapts%20the%20default%20behavior%20so%20that%20the%20build%20proceeds%20only%20if%20there%20are%20changes%20within%20the%20blog%2D1%20or%20common%20directories.

ci: only trigger docs preview on demand

---

packages/core/README.md
packages/core/package.json
packages/create-rslib/README.md
packages/create-rslib/package.json
packages/plugin-dts/README.md
packages/plugin-dts/package.json

Update domain, we will use https://lib.rsbuild.dev/ for Rslib.

docs: update domain

---

.changeset/silent-cobras-sing.md
CONTRIBUTING.md
e2e/cases/auto-external/index.test.ts
e2e/cases/bundle-false/index.test.ts
e2e/cases/externals/index.test.ts
e2e/cases/resolve/index.test.ts
e2e/cases/transform-import/index.test.ts
e2e/package.json
examples/react-component/package.json
packages/core/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
website/package.json

chore: bump rsbuild 1.0.3

---

e2e/cases/syntax/index.test.ts
packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap

Fix https://github.com/web-infra-dev/rslib/issues/209.
- only webpack runtime related code will be affected.
- need to manually assign `{type}loading` as it derive the value from `target` by default, which will lead to unimpelmented `universal` type.

fix: derive `rspack.target` from `libConfig.syntax`

---

e2e/cases/shims/cjs/package.json
e2e/cases/shims/cjs/rslib.config.ts
e2e/cases/shims/cjs/src/index.ts
e2e/cases/shims/index.test.ts
packages/core/src/config.ts
packages/core/src/plugins/cjsShim.ts
packages/core/tests/__snapshots__/config.test.ts.snap
pnpm-lock.yaml

This Rsbuild plugin will shim `import.meta.url` for CommonJS modules.
- Replace `import.meta.url` with `importMetaUrl`.
- Inject `importMetaUrl` to the end of the module (can't inject at the beginning because of `"use strict";`).
This is a short-term solution, and we hope to provide built-in polyfills like `node.__filename` on Rspack side.

feat: support `import.meta.url` shim for CJS

---

e2e/cases/shims/cjs/rslib.config.ts
e2e/cases/shims/index.test.ts
packages/core/src/plugins/cjsShim.ts

IIUC, it could fix https://github.com/web-infra-dev/rslib/issues/233. cc @chenjiahan , is this the bug that this PR fixes, as described in that issue?

fix: CJS shims should not affect other environments

---

e2e/cases/shims/esm/rslib.config.ts
e2e/cases/shims/index.test.ts
package.json
packages/core/src/config.ts
packages/core/src/utils/syntax.ts
packages/core/tests/syntax.test.ts

fix: do not transform esX for rspack.target field

---

.github/workflows/test-ubuntu.yml
.github/workflows/test-windows.yml
e2e/cases/examples-e2e/react-component/index.pw.test.ts
e2e/cases/examples-e2e/react-component/package.json
e2e/cases/examples-e2e/react-component/rsbuild.config.ts
e2e/cases/examples-e2e/react-component/src/App.tsx
e2e/cases/examples-e2e/react-component/src/index.tsx
e2e/cases/examples-e2e/react-component/tsconfig.json
e2e/package.json
e2e/playwright.config.ts
e2e/scripts/rsbuild.ts
examples/react-component/package.json
pnpm-lock.yaml

test(e2e): add react-component example test

---

.github/renovate.json5

`matchPackageNames` is no longer on https://docs.renovatebot.com/configuration-options/#matchpackagenames.

chore: update renovate

---

packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
pnpm-lock.yaml
tests/integration/async-chunks/default/package.json
tests/integration/async-chunks/default/rslib.config.ts
tests/integration/async-chunks/default/src/dynamic.js
tests/integration/async-chunks/default/src/index.js
tests/integration/async-chunks/index.test.ts

Fix https://github.com/web-infra-dev/rslib/issues/254.

fix: use ESM chunkLoading for "esm" format

---

packages/core/src/config.ts
packages/core/src/types/config/index.ts
tests/integration/dts/__snapshots__/index.test.ts.snap
tests/integration/dts/bundle-false/auto-extension/rslib.config.ts
tests/integration/dts/bundle-false/basic/rslib.config.ts
tests/integration/dts/bundle/auto-extension/rslib.config.ts
tests/integration/dts/bundle/basic/rslib.config.ts
tests/integration/dts/index.test.ts

For common usage, using `.d.ts` is sufficient for most cases. `autoExtension` is broken for non module type package now (see https://github.com/web-infra-dev/rslib/issues/263). This PR disable it by default, we might switch it back in the future.

fix(dts): disable autoExtension for dts by default

---

.github/workflows/lint.yml
.github/workflows/release-pull-request.yml
.github/workflows/release.yml
.github/workflows/test-ubuntu.yml
.github/workflows/test-windows.yml

Ref: https://github.com/web-infra-dev/rslib/pull/266#issuecomment-2404134989
- lock benchmark node version
- run integration tests on 18 20 22
- clean ci

ci: clean up and lock benchmark node version

---

.github/workflows/test-ubuntu.yml
.github/workflows/test-windows.yml
cspell.config.cjs
package.json
scripts/dictionary.txt

https://cspell.org/docs/globs/

chore: spell check hidden files

---

packages/core/src/plugins/cjsShim.ts
tests/integration/require/index.test.ts
tests/integration/shims/cjs/src/index.ts
tests/integration/shims/index.test.ts

Fix https://github.com/web-infra-dev/rslib/issues/274.

fix: inline `import.meta.url` shims in CJS

---

.github/renovate.json5
package.json
packages/core/package.json
packages/create-rslib/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/package.json

chore: use 0.0.10 to build self

---

packages/core/src/plugins/cjsShim.ts
tests/integration/shims/cjs/rslib.config.ts
tests/integration/shims/cjs/src/index.ts
tests/integration/shims/cjs/src/ok.cjs
tests/integration/shims/index.test.ts
tests/tsconfig.json

Fix https://github.com/web-infra-dev/rslib/issues/274, again 😅.

fix(shim): use `module.require` to avoid variable collision

---

.changeset/proud-sheep-end.md
packages/plugin-dts/src/tsc.ts

fix: pass in projectReferences to avoid missing some error reports

---

examples/react-component-bundle/package.json
packages/core/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/integration/asset/svgr/package.json
tests/package.json
website/package.json

Rsbuild follows semver and it is safe to unpin Rsbuild to allow automatic patch upgrade.
I use `~` instead of `^` because the Rspack minor releases may contain SWC breaking changes.

fix(deps): unpin Rsbuild to allow automatic patch upgrade

---

.github/workflows/release.yml

Previously, it will use the branch of `Use workflow from`. See https://github.com/web-infra-dev/rslib/actions/runs/11339996469/job/31535663657#step:6:19 still releasing on `main` branch although I've set `Release Branch` to another.

ci: fix should publish on selected branch

---

packages/core/package.json
packages/create-rslib/package.json
packages/create-rslib/src/index.ts
packages/plugin-dts/package.json
packages/plugin-dts/src/index.ts
pnpm-lock.yaml

Bump Rslib 0.0.12 and adjust `__dirname` and `__filename`, since Rslib no longer inject shims by default for `__dirname` and `__filename`.

chore: bump Rslib 0.0.12 and adjust dirname/filename

---

package.json
pnpm-lock.yaml
tests/integration/cli/index.test.ts
tests/integration/cli/package.json

This PR partially revert #302. After #302, we can't execute `npx rslib build` under any integrations tests cases.
This PR doesn't revert the goal of #302, just remove the `workspaces` field of the root package.json which is the monorepo field for npm(https://docs.npmjs.com/cli/v7/using-npm/workspaces), this also helps keep single source of truth of the monorepo definition (pnpm-workspace.yaml).
changesets uses https://github.com/Thinkmill/manypkg to find packages in a monorepo under the hood so it could correct resolve pnpm-workspace.yaml. check-dependency-version-consistency could also read it https://github.com/bmish/check-dependency-version-consistency#usage.

chore: remove duplicated workspace definitions

---

packages/core/package.json
packages/core/prebundle.config.mjs
packages/core/rslib.config.ts
packages/core/src/config.ts
packages/core/tsconfig.json
packages/plugin-dts/package.json
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml
scripts/dictionary.txt
tests/package.json
tests/scripts/helper.ts

Tinyglobby is a fast and minimal alternative to globby and fast-glob, it is used by tsup, Vite and Nuxt.
- `tinyglobby` is now in `dependencies` of `@rslib/core` because `rsbuild-plugin-dts` also depends on it. If we prebundle it, there will be two copies of the code.
- Add `absolute: true` because `fast-glob` and `tinyglobby` use different relative formats, `fast-glob` will return `./path/to/file.js`, `tinyglobby` will return `path/to/file.js`. Also the absolute path is more friendly to the Node `fs` APIs.
This PR should reduce 15 sub-dependencies of Rslib:
https://github.com/SuperchupuDev/tinyglobby?tab=readme-ov-file#api

perf(deps): replace fast-glob with tinyglobby

---

.github/renovate.json5

renovate ignore react-aliased since umd globals test need a fixed version of react.

chore: renovate ignore react-aliased

---

website/docs/en/guide/start/quick-start.mdx

Most of the content are copied from Rsbuild. We can add more content in the future.

docs: add quick start doc

---

.github/workflows/test-ubuntu.yml
.github/workflows/test-windows.yml

Previously, if a PR only modify docs (*.md), the required jobs will skip directly as `if: ${{ needs.changes.outputs.changed == 'true' }}`. But the jobs are required for PRs in repository settings.
This PR adds a dedicated job to be the status check job. It will be success if the jobs passed, and pending when failed.
This could also simplify our required status check in repository settings and move it into code.
TODO: required jobs need to be updated after PR got merged.

ci: required checks should always run

---

biome.json
packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
pnpm-lock.yaml
scripts/dictionary.txt
tests/README.md
tests/integration/node-polyfill/bundle-false/package.json
tests/integration/node-polyfill/bundle-false/rslib.config.ts
tests/integration/node-polyfill/bundle-false/src/buffer1.ts
tests/integration/node-polyfill/bundle-false/src/buffer2.ts
tests/integration/node-polyfill/bundle-false/src/index.ts
tests/integration/node-polyfill/bundle-false/tsconfig.json
tests/integration/node-polyfill/bundle/package.json
tests/integration/node-polyfill/bundle/rslib.config.ts
tests/integration/node-polyfill/bundle/src/buffer1.ts
tests/integration/node-polyfill/bundle/src/buffer2.ts
tests/integration/node-polyfill/bundle/src/index.ts
tests/integration/node-polyfill/bundle/tsconfig.json
tests/integration/node-polyfill/index.test.ts
website/docs/en/guide/advanced/_meta.json
website/docs/en/guide/advanced/node-polyfill.mdx

Supersede https://modernjs.dev/module-tools/en/plugins/official-list/plugin-node-polyfill.html.

feat: support node polyfill

---

README.md
website/docs/en/guide/start/index.mdx

add introduction and features doc

docs: add introduction and features doc

---

packages/core/src/utils/syntax.ts
packages/core/tests/syntax.test.ts

fix: map syntax "es6" to "es2015"

---

packages/core/src/config.ts
packages/core/src/types/config/index.ts
packages/create-rslib/template-node-dual-ts/rslib.config.ts
packages/create-rslib/template-node-esm-ts/rslib.config.ts
pnpm-lock.yaml
tests/integration/dts/bundle-false/true/package.json
tests/integration/dts/bundle-false/true/rslib.config.ts
tests/integration/dts/bundle/true/package.json
tests/integration/dts/bundle/true/rslib.config.ts
tests/integration/dts/index.test.ts
tests/scripts/shared.ts

- Support `dts: true` to default generate bundleless DTS
- Only generate bundle DTS when `dts.bundle` set to true

feat: support set `dts: true` and dts default to bundleless

---

packages/plugin-dts/package.json
website/docs/en/guide/start/npm-packages.mdx

docs: add npm packages docs

---

website/docs/en/guide/advanced/node-polyfill.mdx

docs: update node-polyfill.mdx

---

packages/core/src/config.ts

vmok uses `global` by default.
When users use a external pkg like `'@xxx'`, this will be transform to 
```
var xxx = @xxx
```
which will cause syntax Error because there's no quotation marks. So set to global to avoid this
close: https://github.com/web-infra-dev/rslib/issues/330

fix: use global as mf format external type

---

packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts

Emit config file parsing diagnostics in DTS build.
If there is no fileLoc in diagnostics, it should be tsconfig file, align with [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/0fab463b21c6edc4d94834568a3f440241d57887/src/typescript/worker/lib/config.ts#L118-L128)

fix: should emit config file parsing diagnostics in DTS build

---

CONTRIBUTING.md
scripts/generateReleasePr.mjs

1. Run `pnpm generate-release-pr` to create a release pull request.
2. [Run the release action on release branch](https://github.com/web-infra-dev/rslib/actions/workflows/release.yml).
3. Merge the release pull request.
4. [Create Git tag on main branch and generate the release notes](https://github.com/web-infra-dev/rslib/releases).

chore: modify release workflow

---

packages/core/src/cli/commands.ts
tests/integration/cli/index.test.ts
tests/integration/cli/rslib.config.ts
website/docs/en/guide/basic/cli.mdx

modify options of `inspect` command

chore: modify inspect cli commands and add cli commands docs

---

packages/create-rslib/fragments/tools/vitest-react-js/package.json
packages/create-rslib/fragments/tools/vitest-react-ts/package.json
packages/create-rslib/src/helpers.ts
packages/create-rslib/template-[node-dual]-[]-js/package.json
packages/create-rslib/template-[node-dual]-[]-ts/package.json
packages/create-rslib/template-[node-dual]-[vitest]-js/package.json
packages/create-rslib/template-[node-dual]-[vitest]-ts/package.json
packages/create-rslib/template-[node-esm]-[]-js/package.json
packages/create-rslib/template-[node-esm]-[]-ts/package.json
packages/create-rslib/template-[node-esm]-[vitest]-js/package.json
packages/create-rslib/template-[node-esm]-[vitest]-ts/package.json
packages/create-rslib/template-[react]-[]-js/package.json
packages/create-rslib/template-[react]-[]-ts/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/create-rslib/template-[react]-[vitest]-js/package.json
packages/create-rslib/template-[react]-[vitest]-ts/package.json

- leave `workspace:*` to the final step.
- bump testing library

fix(create-rslib): preserve @rslib/core as workspace

---

website/docs/en/config/lib/auto-extension.mdx
website/docs/en/config/lib/auto-external.mdx
website/docs/en/config/lib/banner.mdx
website/docs/en/config/lib/bundle.mdx
website/docs/en/config/lib/dts.mdx
website/docs/en/config/lib/external-helpers.mdx
website/docs/en/config/lib/footer.mdx
website/docs/en/config/lib/format.mdx
website/docs/en/config/lib/redirect.mdx
website/docs/en/config/lib/shims.mdx
website/docs/en/config/lib/syntax.mdx
website/docs/en/config/lib/umd-name.mdx

Complete types and default value for `lib` configs.

docs: complete types and default value for `lib` configs

---

packages/core/bin/rslib.js

Enable Node.js 22 new compile cache in Rslib CLI, this makes Node.js startup faster.
- before:
- after:
- https://nodejs.org/id/blog/release/v22.8.0
- https://github.com/nodejs/node/pull/54501
- https://github.com/web-infra-dev/rsbuild/pull/3627
- https://github.com/web-infra-dev/rspack/pull/8331

perf(CLI): enable Node cache before loading modules

---

packages/core/src/index.ts

chore: export composeCreateRsbuildConfig as utils

---

packages/core/src/types/config/index.ts
website/docs/en/config/lib/auto-extension.mdx
website/docs/en/config/lib/auto-external.mdx
website/docs/en/config/lib/banner.mdx
website/docs/en/config/lib/bundle.mdx
website/docs/en/config/lib/dts.mdx
website/docs/en/config/lib/external-helpers.mdx
website/docs/en/config/lib/footer.mdx
website/docs/en/config/lib/format.mdx
website/docs/en/config/lib/redirect.mdx
website/docs/en/config/lib/syntax.mdx
website/docs/en/config/lib/umd-name.mdx

Add the basic description and JSDoc for lib options.

docs: add basic description and JSDoc for lib options

---

packages/core/src/types/config/index.ts
website/docs/en/config/_meta.json
website/docs/en/config/lib.mdx
website/docs/en/config/lib/_meta.json
website/docs/en/config/lib/auto-extension.mdx
website/docs/en/config/lib/bundle.mdx
website/docs/en/config/lib/format.mdx
website/docs/en/config/rsbuild.mdx
website/docs/en/guide/basic/configure-rslib.mdx
website/docs/en/guide/basic/output-format.mdx

add lib.bundle/format/autoExtension doc

docs: add lib.bundle/format/autoExtension doc

---

website/docs/en/config/lib/auto-external.mdx
website/docs/en/guide/advanced/third-party-deps.mdx

docs: lib.autoExternal

---

website/docs/en/guide/migration/modernjs-module.mdx

This PR adds documentation regarding the migration of Modern.js Module projects to Rslib
closes: https://github.com/web-infra-dev/rslib/issues/377

docs: add Modern.js Module migration docs

---

packages/core/src/types/config/index.ts
website/docs/en/config/lib/auto-external.mdx
website/docs/en/config/lib/banner.mdx
website/docs/en/config/lib/external-helpers.mdx
website/docs/en/config/lib/footer.mdx
website/docs/en/config/lib/redirect.mdx
website/docs/en/config/lib/shims.mdx
website/docs/en/config/lib/syntax.mdx
website/docs/en/config/lib/umd-name.mdx

Add docs of lib:
- redirect
- syntax
- externalHelpers
- banner
- footer
- umdName

docs: add redirect/syntax/externalHelpers/banner/footer/umdName lib config

---

website/docs/en/guide/migration/_meta.json
website/docs/en/guide/migration/tsup.mdx
website/docs/en/guide/start/quick-start.mdx

Add a basic migration guide for tsup.

docs: tsup migration guide

---

website/docs/en/guide/basic/cli.mdx

docs: mf dev cli commands

---

examples/module-federation/mf-react-component/rslib.config.ts
packages/core/src/config.ts

Target of mf format should be web, or will create break change.
Users should not specifically config target to 'web' in their projects

fix: target of mf format should be web

---

packages/core/src/config.ts
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
pnpm-lock.yaml
tests/integration/dts/bundle-false/declaration-dir/package.json
tests/integration/dts/bundle-false/declaration-dir/rslib.config.ts
tests/integration/dts/bundle-false/declaration-dir/tsconfig.json
tests/integration/dts/index.test.ts

The bundleless dts emit path should follow priority of:
1. `dts.distPath`
2. `declarationDir`
3. `output.distPath.root`

fix: respect declarationDir if dts.distPath is not set

---

website/docs/en/guide/migration/modernjs-module.mdx

docs: update css-modules to CSS Modules

---

.changeset/silver-pumas-tap.md
packages/core/src/utils/helper.ts
packages/core/tests/helper.test.ts

plugins may pass array type like this: 
```ts
{
format: 'mf',
plugins: [
[
{ name: 'rsbuild:module-federation-enhanced', setup: () => {} },
{ name: 'plugin-foo', setup: () => {} },
],
],
}
```

fix: checkMFPlugin function support array plugins

---

packages/plugin-dts/src/tsc.ts
pnpm-lock.yaml
tests/integration/dts/composite/__fixtures__/src/index.ts
tests/integration/dts/composite/__fixtures__/src/sum.ts
tests/integration/dts/composite/__fixtures__/src/utils/numbers.ts
tests/integration/dts/composite/__fixtures__/src/utils/strings.ts
tests/integration/dts/composite/abort-on-error/package.json
tests/integration/dts/composite/abort-on-error/rslib.config.ts
tests/integration/dts/composite/abort-on-error/src/const.ts
tests/integration/dts/composite/abort-on-error/src/index.ts
tests/integration/dts/composite/abort-on-error/tsconfig.json
tests/integration/dts/composite/basic/package.json
tests/integration/dts/composite/basic/rslib.config.ts
tests/integration/dts/composite/basic/tsconfig.json
tests/integration/dts/composite/dist-path/package.json
tests/integration/dts/composite/dist-path/rslib.config.ts
tests/integration/dts/composite/dist-path/tsconfig.json
tests/integration/dts/composite/process-files/package.json
tests/integration/dts/composite/process-files/rslib.config.ts
tests/integration/dts/composite/process-files/tsconfig.json
tests/integration/dts/index.test.ts

Our current logic using the [Typescript compiler API](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#writing-an-incremental-program-watcher) is:
1. `dts.build: false`: [basic compiler](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler) with `createCompilerHost` and `createProgram`
2. `dts.build: true`: incremental build with project references, using `createSolutionBuilderHost` and `createSolutionBuilder`
1. `dts.build: false`: [incremental program watcher](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#writing-an-incremental-program-watcher) with `createWatchCompilerHost` and `createWatchProgram`
2. `dts.build: true`: incremental build with project references, using `createSolutionBuilderWithWatchHost` and …

feat: support incremental build when composite is true

---

packages/core/package.json
packages/core/src/css/RemoveCssExtractAssetPlugin.ts
packages/core/src/css/libCssExtractLoader.ts
packages/core/src/plugins/entryModuleLoader.ts
pnpm-lock.yaml

remove unnecessary rspack/core devDeps to avoid rspack multiple versions.

chore(deps): remove unnecessary rspack/core devDeps

---

.github/workflows/test-ubuntu.yml
.github/workflows/test-windows.yml

chore: use specific name for check ci passed

---

pnpm-lock.yaml
tests/integration/polyfill/index.test.ts
tests/integration/polyfill/package.json
tests/integration/polyfill/rslib.config.ts
tests/integration/polyfill/src/index.ts
website/docs/en/guide/advanced/output-compatibility.mdx

Add polyfill docs and test, we still need to use Babel before SWC supports pure polyfill mode (https://redirect.github.com/swc-project/swc/issues/5584).

docs: add browser polyfill

---

packages/core/src/types/config/index.ts

Close https://github.com/web-infra-dev/rslib/issues/445.
Prefer to use [TSDoc](https://tsdoc.org/) as it's doc comments for TypeScript.

fix: add tsdoc for config options

---

website/docs/en/config/rsbuild.mdx
website/docs/en/config/rsbuild/source.mdx
website/theme/components/RsbuildDocBadge.tsx

Options that are not applicable are currently commented out (`preEntry`).

docs: add config.rsbuild.source

---

examples/module-federation/mf-host/package.json
examples/module-federation/mf-remote/package.json
package.json
packages/core/package.json
packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
packages/create-rslib/fragments/tools/storybook-react-js/package.json
packages/create-rslib/fragments/tools/storybook-react-ts/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/integration/externals/index.test.ts
tests/integration/externals/node/rslib.config.ts
tests/integration/externals/node/src/baz.mjs
tests/integration/externals/node/src/index.ts
tests/package.json
website/package.json

It's hard to cover all cases of whether it's under node `13.2.0` without calling Browserslist API. Since Node 13.2 has reach EOL for years (https://endoflife.date/nodejs). I think it's fine to set `commonjs-import` as the default external type for Node.js and demonstrate the differences between the externals type on library build scenario next.
Also bump Rsbuild to `~1.1.4`

feat!: use 'commonjs-import' as CJS external type by default

---

packages/core/src/config.ts
tests/integration/bundle-false/index.test.ts
tests/integration/bundle-false/js-extension/rslib.config.ts

fix: js request when using `autoExtension: false` along with `output.filename.js`

---

.github/workflows/test.yml
examples/module-federation/README.md
examples/module-federation/mf-host/README.md
examples/module-federation/mf-react-component/README.md
examples/module-federation/mf-remote/README.md
examples/module-federation/package.json
website/docs/en/guide/advanced/module-federation.mdx
website/docs/en/guide/advanced/storybook.mdx
website/docs/en/guide/start/components/MF.mdx
website/docs/en/guide/start/glossary.mdx

docs(mf): polish docs

---

examples/vue-component-bundle/README.md
examples/vue-component-bundle/package.json
examples/vue-component-bundle/rslib.config.ts
examples/vue-component-bundle/src/Counter.vue
examples/vue-component-bundle/src/CounterButton.vue
examples/vue-component-bundle/src/index.ts
examples/vue-component-bundle/tsconfig.json
pnpm-lock.yaml

Add a vue-component-bundle example:
- Use [vue-tsc](https://www.npmjs.com/package/vue-tsc) to generate .d.ts.
- Use [@rsbuild/plugin-vue](https://www.npmjs.com/package/@rsbuild/plugin-vue) to support SFC.
- Only bundle mode is now supported.
Preview:

chore(examples): add vue-component-bundle example

---

examples/react-component-bundle/rslib.config.ts
examples/vue-component-bundle/rslib.config.ts
packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
tests/integration/style/css-modules/index.test.ts
tests/integration/style/css/index.test.ts
tests/integration/style/less/index.test.ts
tests/integration/style/lightningcss/index.test.ts
tests/integration/style/postcss/index.test.ts
tests/integration/style/sass/index.test.ts
tests/integration/style/tailwindcss/index.test.ts

Emit CSS files and async files to `dist` instead of `dist/static/css`.
- Align with `distPath.js`.
- Usually library authors prefer flatter output instead of nested output.

feat!: emit CSS files to `dist` instead of `dist/static/css`

---

website/docs/en/guide/advanced/_meta.json
website/docs/en/guide/start/_meta.json
website/docs/en/guide/start/index.mdx
website/theme/index.tsx

docs: hide some unfinished docs

---

packages/core/src/config.ts
packages/core/src/types/config/index.ts
packages/core/tests/entry.test.ts

Correctly handle all possible entry types to add entry query. Previously, we can only handle `string` indeed.

fix: entry query should handle non-string entry

---

tests/integration/entry/index.test.ts
tests/integration/entry/multiple/rslib.config.ts
tests/integration/entry/multiple/src/foo.ts
tests/integration/entry/multiple/src/index.ts
tests/integration/entry/multiple/src/shared.ts
tests/scripts/shared.ts

Finish the test of multiple entry, resolved by https://github.com/web-infra-dev/rslib/pull/399.
https://github.com/web-infra-dev/rslib/pull/399 fixed https://github.com/web-infra-dev/rslib/issues/316.
https://github.com/web-infra-dev/rslib/pull/399 fixed https://github.com/web-infra-dev/rslib/issues/452.
In #399, each entry is appended with a `?__rslib_entry__` query so importing `foo` from `index` will be distinguished as a different module from the entry module. Which will prevent `foo` from concatenation bailout.
FYI: `layer` could also distinguish the entry module, we might, could use `layer` if one day entry query is removed.
Currently, chunk splitting of shared modules is not yet supported, but at least it works for now. We will track the progress of chunk splitting in a dedicated …

test: multiple entries now do not affect each other

---

.changeset/smooth-parents-pull.md
packages/core/src/cli/mf.ts
packages/core/src/config.ts
scripts/dictionary.txt
tests/integration/minify/index.test.ts

When format is mf , and env is production , the moduleIds should be deterministic for better cache and smaller size. 
And the named moduleIds may cause domain name leaked if the build env path has sensitive infomation

fix: the moduleIds should be deterministic if the env is production and format is mf

---

.gitignore
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml
tests/integration/dts/build/clean/package.json
tests/integration/dts/build/clean/rslib.config.ts
tests/integration/dts/build/clean/src/index.ts
tests/integration/dts/build/clean/src/sum.ts
tests/integration/dts/build/clean/tsconfig.cjs.json
tests/integration/dts/build/clean/tsconfig.esm.json
tests/integration/dts/bundle-false/clean/package.json
tests/integration/dts/bundle-false/clean/rslib.config.ts
tests/integration/dts/bundle/clean/package.json
tests/integration/dts/bundle/clean/rslib.config.ts
tests/integration/dts/composite/clean/package.json
tests/integration/dts/composite/clean/rslib.config.ts
tests/integration/dts/composite/clean/tsconfig.json
tests/integration/dts/index.test.ts
tests/scripts/shared.ts

- Load tsconfig in plugin hook in main process instead of child process
- When using bundle DTS, temporary folders are distinguished by the environment name
- When `output.cleanDistPath` is not set to `false`, clean `.d.ts/mts/cts` files in dts distPath
- Always clean `.rslib` temp folder when `dts.bundle` set to `true`
- Always clean `tsconfig.buildinfo` file
closes: #405 
closes: #139

feat: clean dts files / buildinfo / .rslib temp folder

---

packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/utils.ts

only remove buildinfo when `composite` or `incremental` is set or `dts.build` is set to `true`
closes: #493

perf: rm buildinfo on demand

---

packages/core/src/cli/restart.ts

https://github.com/web-infra-dev/rslib/pull/489

fix: lazy import chokidar

---

.gitignore
tests/integration/cli/build-watch/build.test.ts

https://github.com/web-infra-dev/rslib/pull/500/files#diff-a504a60331f66d3f019aa36e926141ebf4b9c3e7a2311bde4b2d185ea409cd66

test: fix unstable build watch case

---

packages/core/tests/__snapshots__/config.test.ts.snap
packages/core/tests/config.test.ts
tests/integration/alias/rslib.config.ts
tests/integration/style/less/bundle-false/rslib.config.ts
tests/integration/style/less/bundle/rslib.config.ts

We need to update docs in https://lib.rsbuild.dev/config/rsbuild/source#sourcealias in the future, the Rsbuild docs of `resolve.alias` and `resolve.aliasStrategy` is not ready now.
feat: add resolve.alias and deprecate source.alias by @chenjiahan in https://github.com/web-infra-dev/rsbuild/pull/4098

chore: use `resolve.alias` instead of `source.alias`

---

packages/plugin-dts/src/index.ts

silent dts kill error, such as: kill EPERM error on windows.

fix:  catch error when killing DTS child process

---

packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
tests/integration/umd/index.test.ts
tests/integration/umd/src/index.js
tests/integration/umd/src/utils.js
website/docs/en/guide/basic/cli.mdx

do not preserve nodeEnv when format is umd

feat: do not preserve nodeEnv when format is umd

---

website/docs/en/guide/basic/cli.mdx
website/docs/zh/guide/basic/cli.mdx

Translate `cli.mdx` to Chinese and polish the English documentation.

docs: translate cli.mdx to Chinese

---

website/docs/en/guide/migration/modernjs-module.mdx
website/docs/en/guide/migration/tsup.mdx
website/docs/zh/guide/advanced/output-compatibility.mdx
website/docs/zh/guide/basic/output-format.mdx
website/docs/zh/guide/basic/output-structure.mdx
website/docs/zh/guide/migration/modernjs-module.mdx
website/docs/zh/guide/migration/tsup.mdx

docs: translate migration docs

---

packages/core/src/types/config/index.ts
website/docs/en/config/lib/auto-extension.mdx
website/docs/en/config/lib/auto-external.mdx
website/docs/en/config/lib/banner.mdx
website/docs/en/config/lib/dts.mdx
website/docs/en/config/lib/external-helpers.mdx
website/docs/en/config/lib/footer.mdx
website/docs/en/config/lib/format.mdx
website/docs/en/config/lib/shims.mdx
website/docs/en/config/lib/syntax.mdx
website/docs/zh/config/lib/auto-extension.mdx
website/docs/zh/config/lib/auto-external.mdx
website/docs/zh/config/lib/banner.mdx
website/docs/zh/config/lib/bundle.mdx
website/docs/zh/config/lib/dts.mdx
website/docs/zh/config/lib/external-helpers.mdx
website/docs/zh/config/lib/footer.mdx
website/docs/zh/config/lib/format.mdx
website/docs/zh/config/lib/id.mdx
website/docs/zh/config/lib/redirect.mdx
website/docs/zh/config/lib/shims.mdx
website/docs/zh/config/lib/syntax.mdx
website/docs/zh/config/lib/umd-name.mdx

docs(zh): translate /config/lib to Chinese

---

website/docs/en/guide/basic/configure-rslib.mdx
website/docs/zh/guide/basic/configure-rslib.mdx

- Translate configure-rslib to Chinese
- Simplify the `Configuration Structure` section.

docs: translate configure-rslib

---

website/docs/zh/config/lib/footer.mdx

docs: preserve footer keyword

---

website/docs/en/config/rsbuild/index.mdx
website/docs/en/config/rsbuild/output.mdx
website/docs/en/config/rsbuild/resolve.mdx
website/docs/en/config/rsbuild/source.mdx
website/docs/en/config/rsbuild/tools.mdx
website/docs/zh/config/rsbuild/index.mdx
website/docs/zh/config/rsbuild/output.mdx
website/docs/zh/config/rsbuild/resolve.mdx
website/docs/zh/config/rsbuild/source.mdx
website/docs/zh/config/rsbuild/tools.mdx

Translate Rsbuild configurations to Chinese.

docs: translate Rsbuild configurations

---

website/docs/en/config/rsbuild/plugins.mdx
website/docs/zh/config/rsbuild/plugins.mdx

Translate plugins configuration to Chinese.

docs: translate plugins configuration

---

packages/core/src/cli/build.ts
packages/core/src/cli/inspect.ts
packages/core/src/cli/mf.ts
packages/core/src/config.ts
packages/core/src/utils/helper.ts
pnpm-lock.yaml
tests/integration/plugins/index.test.ts
tests/integration/plugins/package.json
tests/integration/plugins/rslib.config.ts
tests/integration/plugins/src/index.ts

I found this issue when testing [rsbuild-plugin-publint](https://github.com/rspack-contrib/rsbuild-plugin-publint).
In Rsbuild, shared plugins will run only once. Take `rsbuild-plugin-publint` as an example, it uses `api.onAfterBuild` to trigger the linting, and this should only be triggered once per build, otherwise it will result in duplicate lint output.
```ts
// rsbuild.config.ts
export default {
// this is a shared plugin
plugins: [publintPlugin],
environments: {
client: {
plugins: [clientOnlyPlugin],
},
server: {
plugins: [serverOnlyPlugin],
},
},
};
```
Currently Rslib does not align with this behavior, the shared plugins are registered multiple times. After this PR, Rslib will be aligned with Rsbuild.

fix: shared Rsbuild plugins should run only once

---

website/docs/en/guide/advanced/storybook.mdx
website/docs/zh/guide/advanced/storybook.mdx

docs(zh): translate use storybook

docs(zh): translate use storybook

---

packages/create-rslib/fragments/tools/storybook-react-js/.storybook/main.js
packages/create-rslib/fragments/tools/storybook-react-ts/.storybook/main.ts
packages/create-rslib/template-[react]-[storybook,vitest]-js/.storybook/main.js
packages/create-rslib/template-[react]-[storybook,vitest]-ts/.storybook/main.ts
packages/create-rslib/template-[react]-[storybook]-js/.storybook/main.js
packages/create-rslib/template-[react]-[storybook]-ts/.storybook/main.ts

Use `getAbsolutePath` in template to correctly resolve `storybook-addon-rslib` in pnpm.

fix(create-rslib): correctly resolve `storybook-addon-rslib` in pnpm

---

website/docs/en/guide/solution/nodejs.mdx
website/docs/zh/guide/solution/nodejs.mdx

docs: config name typo

---

packages/core/rslib.config.ts

closes: #567 
Fix cannot import typing issue when `"moduleResolution": "NodeNext"` in user's `tsconfig.json` by adding an empty `package.json` to the `dist-types` folder.
https://github.com/web-infra-dev/rsbuild/pull/2353

fix: type missing when set moduleResolution node16+

---

website/docs/en/config/rsbuild/plugins.mdx
website/docs/zh/config/rsbuild/plugins.mdx

docs(plugins): add publint plugin

---

examples/preact-component-bundle-false/src/index.tsx
examples/react-component-bundle-false/src/index.tsx
examples/react-component-bundle/src/index.tsx
examples/react-component-umd/src/index.tsx

Now, we have https://github.com/web-infra-dev/rslib/pull/535, so mainFiles can be not specified

test(example): remove `index`, mainFiles can be not specified

---

packages/core/src/cli/build.ts
packages/core/src/cli/inspect.ts
packages/core/src/cli/mf.ts
packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/server/basic/package.json
tests/integration/server/basic/rslib.config.ts
tests/integration/server/basic/src/index.ts
tests/integration/server/index.test.ts
tests/integration/server/mf-dev/package.json
tests/integration/server/mf-dev/rslib.config.ts
tests/integration/server/mf-dev/src/index.ts

We should pass `server` config to Rsbuild since `mf dev` and some `publicDir` feature need to configure it.
fix: #583

fix: pass server config to Rsbuild

---

tests/integration/alias/__snapshots__/index.test.ts.snap
tests/integration/alias/index.test.ts
tests/integration/alias/rslib.config.ts
tests/integration/redirect/js.test.ts
tests/integration/redirect/js/rslib.config.ts
tests/integration/server/index.test.ts
website/docs/en/config/lib/redirect.mdx
website/docs/en/config/rsbuild/resolve.mdx
website/docs/zh/config/lib/redirect.mdx
website/docs/zh/config/rsbuild/resolve.mdx

In bundleless mode, since there is no bundling concept, all modules will be externalized, so we will automatically replace the aliases in `resolve.alias` with `output.externals` to ensure the final output is generated correctly.

test: add alias replace externals tests in bundleless mode

---

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
.github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
.github/workflows/pr-label.yaml

1. Since the `pr-labeler` workflow adds labels to pull requests, it needs the `pull-requests: write` permission.
2. The GitHub issue types work well and we can remove the issue label to reduce duplicated information.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#overview

chore(CI): correct permissions for issue labeler

---

tests/integration/cli/mf-dev/dev.test.ts
tests/integration/cli/mf-dev/rslib.config.ts
tests/integration/server/index.test.ts
tests/integration/server/mf-dev/rslib.config.ts

test: stabilize mf-dev tests

---

CONTRIBUTING.md

docs: modify release steps

---

.github/workflows/pr-label.yaml
.github/workflows/release.yml

Provenance generation in GitHub Actions requires "write" access to the "id-token" and I should not delete it.
I have added comment to prompt the role of this permission.

chore(CI): fix missing permission for provenance

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/redirect/js-not-resolve/package.json
tests/integration/redirect/js-not-resolve/rslib.config.ts
tests/integration/redirect/js-not-resolve/src/index.js
tests/integration/redirect/js.test.ts
tests/integration/redirect/jsNotResolved.test.ts
tests/scripts/shared.ts

Given that if a React component library, but `"react"` is not defined in either `devDeps` or `peerDeps`, the requested `"react"` in `import { useEffect } from 'react'` can't be resolved at all, so we should directly skipping process it and emit a warning to users.

fix: do not handle the path that can’t be resolved

---

website/docs/en/guide/faq/features.mdx
website/docs/zh/guide/faq/features.mdx

docs: add how to skip the preprocessing of `less/scss` files
#614

docs: add how to skip the preprocessing of `less/scss` files

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/auto-external/bundle-false/package.json
tests/integration/auto-external/bundle-false/rslib.config.ts
tests/integration/auto-external/bundle-false/src/index.ts
tests/integration/auto-external/bundle-false/tsconfig.json
tests/integration/auto-external/index.test.ts
tests/integration/redirect/js-not-resolve/src/index.js
tests/integration/redirect/js.test.ts
tests/integration/redirect/js/src/index.ts
tests/integration/redirect/jsNotResolved.test.ts
website/docs/en/config/lib/auto-external.mdx
website/docs/en/config/lib/redirect.mdx
website/docs/en/guide/advanced/third-party-deps.mdx
website/docs/zh/config/lib/auto-external.mdx
website/docs/zh/config/lib/redirect.mdx
website/docs/zh/guide/advanced/third-party-deps.mdx

- **breaking changes**: `autoExternal` only takes effect in bundle mode now
- only redirect request not in node_modules
closes: #616

feat!: disable `autoExternal` in bundleless mode and only redirect request not in node_modules

---

packages/core/src/constant.ts
packages/core/tests/constant.test.ts
tests/integration/entry/glob/src/global.d.ts

Close https://github.com/web-infra-dev/rslib/issues/635.

fix: do not treat .d.ts as entry

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/entry/glob-bundle/package.json
tests/integration/entry/glob-bundle/rslib.config.ts
tests/integration/entry/glob-bundle/src/bar.ts
tests/integration/entry/glob-bundle/src/foo.ts
tests/integration/entry/index.test.ts

Close https://github.com/web-infra-dev/rslib/issues/632.
> > Glob pattern entry like .src/** must be set along with bundle: false.
> 
> I think we could do an active detection here.

fix: detect possible glob pattern in bundle more

---

packages/core/src/config.ts
packages/core/src/plugins/EntryChunkPlugin.ts
packages/core/tests/__snapshots__/config.test.ts.snap
tests/integration/cli/build-watch/build.test.ts
tests/integration/cli/build-watch/rslib.config.ts
tests/integration/cli/build-watch/src/index.ts
tests/integration/directive/index.test.ts
tests/integration/directive/react/bundleless/rslib.config.ts
tests/scripts/helper.ts

Previously, the `entry` in bundleless mode is set during the initial build and does not change during the `rslib build --watch` phase. For example, a newly added file will not be monitored, while a file that was included initially will trigger an error (entry module not found) if it is deleted later.
In this PR, we use two combined functionality to resolve the issue:
1. Dynamic entry (https://rspack.dev/config/entry#dynamic-entry): a callback that will revoked when watch build is triggered every time that give us a chance to re-scan the entires.
2. `compilation.contextDependencies`: an extra directory to watch and trigger watch build (e.g. used in https://github.com/soda-x/extra-watch-webpack-plugin)
Limitation:
- `compilation.contextDependencies` will be resolved at the very beginning by …

fix: handle add and unlink file in bundleless mode

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/entry/default/package.json
tests/integration/entry/default/rslib.config.ts
tests/integration/entry/default/src/foo.ts
tests/integration/entry/default/src/index.ts
tests/integration/entry/index.test.ts
website/docs/en/config/lib/bundle.mdx
website/docs/en/config/rsbuild/source.mdx
website/docs/zh/config/lib/bundle.mdx
website/docs/zh/config/rsbuild/source.mdx

set entry default to `src/**` in bundleless mode
close: #638

feat: entry default to `src/**` in bundleless mode

---

packages/core/src/cli/mf.ts
packages/core/src/config.ts
tests/integration/cli/build/build.test.ts
tests/integration/cli/mf/mf.test.ts

Throw error when
- No configuration match `--lib` option
- No `format: 'mf'` when `npx rslib mf-dev`

feat: throw error when no configuration match `--lib` option

---

website/docs/en/config/rsbuild/output.mdx
website/docs/en/config/rsbuild/source.mdx
website/docs/zh/config/rsbuild/output.mdx
website/docs/zh/config/rsbuild/source.mdx

Introduce the different default values between Rslib and Rsbuild.
> not contain builtin Rspack configuration, this is too complex.
closes: #626

docs: introduce the different default values between Rslib and Rsbuild

---

examples/preact-component-bundle-false/rslib.config.ts
examples/react-component-bundle-false/rslib.config.ts

`*.d.ts` is excluded by default in bundleless mode.

chore: remove manually d.ts excluding

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/externals/index.test.ts
tests/integration/externals/user-externals/package.json
tests/integration/externals/user-externals/rslib.config.ts
tests/integration/externals/user-externals/src/foo.js
tests/integration/externals/user-externals/src/index.js

Fix bug introduced in https://github.com/web-infra-dev/rslib/pull/535/files#diff-4114b8f08217be27efd35a3891857cfabc6eb75aee8ab39ba304e4d1b1095323R1317.
User's externals config should take higher priority to matched earlier than `autoExternalConfig` and others.

fix: user externals should have higher priority

---

website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/start/quick-start.mdx

add docs about how to migrate from existing projects.
closes: #655

docs: how to migrate from existing projects

---

examples/preact-component-bundle-false/rslib.config.ts
examples/react-component-bundle-false/rslib.config.ts
packages/create-rslib/package.json
pnpm-lock.yaml

ts error in fragments of template is acceptable

chore: remove unused `@rslib/core` to avoid nx cache error

---

.github/workflows/test.yml
package.json
packages/core/package.json
packages/core/src/utils/syntax.ts
packages/core/tests/config.test.ts
packages/core/tests/extension.test.ts
packages/core/tests/external.test.ts
packages/core/tests/syntax.test.ts
packages/core/tests/tsconfig.json
tests/integration/async-chunks/index.test.ts
tests/package.json
tests/tsconfig.json

Close https://github.com/web-infra-dev/rslib/issues/458.

chore: add type check for test files

---

packages/core/src/config.ts
tests/integration/entry/index.test.ts
tests/integration/entry/validate/bundlelessWithString.config.ts
website/docs/en/config/rsbuild/source.mdx
website/docs/zh/config/rsbuild/source.mdx

validate entry type to prevent unexpected behaviour.

fix: validate entry type

---

examples/react-component-bundle-false/rslib.config.ts
packages/core/src/css/libCssExtractLoader.ts
pnpm-lock.yaml
tests/integration/sourcemap/css/package.json
tests/integration/sourcemap/css/rslib.config.ts
tests/integration/sourcemap/css/src/index.css
tests/integration/sourcemap/index.test.ts

close: https://github.com/web-infra-dev/rslib/issues/595

fix: emit css source map in bundleless mode

---

packages/plugin-dts/src/index.ts

Before this PR, if users want to do something in plugins that written by themselves, they should explicitly set `order: 'post'` when they call `onAfterBuild` hook. 
This PR use `pre` to avoid this scene.

fix: use pre hook order to promise dts task

---

website/docs/en/guide/faq/features.mdx
website/docs/zh/guide/faq/features.mdx

Real world example https://github.com/web-infra-dev/rspress/pull/1770/files#diff-605f1ec46dc20df4ee9c502cd9c8b342db2c6ec5b3d7dd40b0fc8aad00fc0673R26.

docs(QA): add how to external module in DTS

---

packages/core/src/config.ts
packages/core/src/css/cssConfig.ts
packages/core/src/css/libCssExtractLoader.ts
tests/integration/banner-footer/rslib.config.ts
tests/integration/banner-footer/src/index.ts
tests/integration/style/css-modules/index.test.ts
tests/integration/style/stylus/index.test.ts

Support adding banner and footer in bundleless emitted css in loader.
close: https://github.com/web-infra-dev/rslib/issues/265

feat: support banner and footer in bundleless emitted css

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/entry/duplicate/package.json
tests/integration/entry/duplicate/rslib.config.ts
tests/integration/entry/duplicate/src/index.css
tests/integration/entry/duplicate/src/index.module.css
tests/integration/entry/duplicate/src/index.ts
tests/integration/entry/index.test.ts

For duplicate entries in bundleless mode, we already deal with css files which is common to have same name in library development. But for some static assets, which usually not appear at the same level of Javascript files, this PR log a warning if they are in the same level as what Javascript files locates.
close: #199

fix: warn duplicate entries in bundleless mode

---

.github/workflows/benchmark.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml

Add `npm install -g corepack@latest --force` before `corepack enable` to fix corepack key id mismatch issue.
> `--force` to prevent windows install error
https://github.com/nodejs/corepack/issues/612

ci(corepack): fix corepack key id mismatch

---

examples/preact-component-bundle-false/src/env.d.ts
examples/react-component-bundle-false/src/env.d.ts
examples/react-component-bundle/src/env.d.ts
examples/react-component-umd/src/env.d.ts
packages/core/package.json
packages/core/tsconfig.json
packages/core/types.d.ts
website/docs/en/guide/migration/modernjs-module.mdx
website/docs/zh/guide/migration/modernjs-module.mdx

for `src/env.d.ts`
1.
```ts
// src/env.d.ts
declare module '*.module.scss' {
const classes: { [key: string]: string };
export default classes;
}
declare module '*.svg' {
const url: string;
export default url;
}
```
2.
```ts
/// <reference types="@rslib/core/types" />
```
https://rsbuild.dev/zh/guide/basic/static-assets#%E7%B1%BB%E5%9E%8B%E5%A3%B0%E6%98%8E

feat(core): reexport "@rslib/core/types" from "@rsbuild/core/types"

---

packages/plugin-dts/src/index.ts
pnpm-lock.yaml
tests/integration/dts/bundle-false/tsconfig-path/package.json
tests/integration/dts/bundle-false/tsconfig-path/rslib.config.ts
tests/integration/dts/index.test.ts

The tsconfig path might not be `tsconfig.json` when it's customized.

fix(dts): correct tsconfig path not found error message

---

packages/core/src/config.ts
packages/core/src/types/config.ts
packages/plugin-dts/README.md
packages/plugin-dts/package.json
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml
tests/integration/redirect/dts.test.ts
tests/integration/redirect/dts/compile/rslog/index.d.ts
tests/integration/redirect/dts/compile/rslog/index.js
tests/integration/redirect/dts/compile/rslog/package.json
tests/integration/redirect/dts/package.json
tests/integration/redirect/dts/rslib.config.ts
tests/integration/redirect/dts/src/foo/foo.ts
tests/integration/redirect/dts/src/index.ts
tests/integration/redirect/dts/src/logger.ts
tests/integration/redirect/dts/src/types.ts
tests/integration/redirect/dts/tsconfig.json
website/docs/en/config/lib/redirect.mdx
website/docs/en/guide/migration/modernjs-module.mdx
website/docs/zh/config/lib/redirect.mdx
website/docs/zh/guide/basic/typescript.mdx
website/docs/zh/guide/migration/modernjs-module.mdx

This PR introduces a new redirect feature about DTS files.
Controls the redirect of the import paths of output Typescript declaration files.
Whether to automatically redirect the import paths of Typescript declaration output files.
- **Type:** `boolean`
- **Default:** `true`
When set to `true`, the [compilerOptions.paths](https://typescriptlang.org/tsconfig#paths) configured in the `tsconfig.json` file will take effect, and the import path of the DTS output file will be redirected to the corresponding relative path.
When set to `false`, the original import path will remain unchanged.
- **Example:**
When `compilerOptions.paths` is set to `{ "@/*": ["src/*"] }` in `tsconfig.json`, the DTS output file will be redirected to the correct relative path:
```ts
import { foo } from '@/foo'; // …
```

feat: support DTS redirect

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml

This PR modifies the CI configuration to ensure that pull requests can merge correctly. The key changes include adjusting the `test.yml` workflow file to improve the CI pipeline's functionality.

chore(CI): modify test ci yaml to make pr merge correctly

---

packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
pnpm-lock.yaml
tests/integration/dts/copy/copy.d.ts
tests/integration/dts/copy/package.json
tests/integration/dts/copy/rslib.config.ts
tests/integration/dts/copy/src/index.ts
tests/integration/dts/copy/tsconfig.json
tests/integration/dts/index.test.ts

This pull request includes several changes to the `packages/plugin-dts` module and some additions to the integration tests. The main focus is on refactoring the `generateDts` function and adding new test configurations.
We should do these clean operations earlier in main process to avoid issue like below when users use `output.copy` to copy some DTS files into assets.

fix: clean dts distPath earlier

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/auto-external/index.test.ts
tests/integration/auto-external/module-import-warn/package.json
tests/integration/auto-external/module-import-warn/rslib.config.ts
tests/integration/auto-external/module-import-warn/src/index.ts

- Correct handle external config with prefixed external type.
- Put user external configs ahead of others to make it be counted first.

fix: correct detect transformed module external request

---

packages/core/src/config.ts
tests/integration/bundle-false/basic/.gitignore
tests/integration/bundle-false/basic/node_modules/dep_add/index.d.ts
tests/integration/bundle-false/basic/node_modules/dep_add/index.js
tests/integration/bundle-false/basic/node_modules/dep_add/package.json
tests/integration/bundle-false/basic/src/dep.ts
tests/integration/bundle-false/basic/src/index.ts
tests/integration/bundle-false/index.test.ts

Fix https://github.com/web-infra-dev/rslib/issues/759.
Previously, in bundleless mode, files in the `root` folder underwent the redirect process. This caused files in the `node_modules` directory of a non-monorepo project, or the project mentioned in #759, to be redirected unexpectedly.
In this PR, only files in the `outBase` directory will go through the redirect process. The `outBase` refers to the directory containing the source files, and only imports between these source files should be redirected.

fix(bundleless): only try to redirect files under outBase dir

---

tests/integration/asset/__snapshots__/index.test.ts.snap
tests/integration/asset/json/src/index.js
website/docs/en/config/rsbuild/output.mdx
website/docs/en/guide/advanced/_meta.json
website/docs/en/guide/advanced/json-files.mdx
website/docs/en/guide/advanced/static-assets.mdx
website/docs/en/guide/advanced/svgr-files.mdx
website/docs/zh/config/rsbuild/output.mdx
website/docs/zh/guide/advanced/_meta.json
website/docs/zh/guide/advanced/json-files.mdx
website/docs/zh/guide/advanced/static-assets.mdx
website/docs/zh/guide/advanced/svgr-files.mdx
website/docs/zh/guide/solution/index.mdx

Add assets, json, svgr usage documents
https://github.com/web-infra-dev/rslib/issues/629

docs(assets): add assets, json, svgr usage document

---

website/docs/en/config/rsbuild/resolve.mdx
website/docs/zh/config/rsbuild/resolve.mdx

docs: add bundleless externals note

---

.github/workflows/preview.yml

Support [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new).
close: #764

chore(CI): support pkg.pr.new

---

.github/workflows/preview.yml

- Run pkg.pr when push to main
- Filter workspaces in pkg-pr-new
#764 
#766

fix(CI): should filter workspaces in pkg-pr-new

---

packages/core/package.json
packages/create-rslib/package.json
packages/plugin-dts/package.json

This release brings exciting new features and improvements to Rslib:
- **DTS Redirect:** Rslib now supports to control the redirect of the import paths in output TypeScript declaration files. (#742)
- [redirect.dts.path](https://lib.rsbuild.dev/config/lib/redirect#redirectdtspath): Redirect the import path in the DTS output file to the corresponding relative path based on the `compilerOptions.paths` configured in `tsconfig.json`.
```ts
// For `compilerOptions.paths` set to `{ "@/*": ["src/*"] }` in `tsconfig.json`
import { foo } from '@/foo'; // source code of './src/bar.ts' ↓
import { foo } from './foo'; // expected output of './dist/bar.d.ts'
import { foo } from '@/foo'; // source code of './src/utils/index.ts' ↓
import { foo } from '../foo'; // expected output './dist/utils/index.d.ts' …
```

Release v0.5.0

---

packages/plugin-dts/src/utils.ts
tests/integration/redirect/dts.test.ts
tests/integration/redirect/dts/src/foo/index.ts
tests/integration/redirect/dts/src/index.ts

Redirect index file when `redirect.dts.extension` is enabled
fix: #775

fix: redirect index file when `redirect.dts.extension` is enabled

---

packages/plugin-dts/src/index.ts
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml
tests/integration/dts/check/outside-root/package.json
tests/integration/dts/check/outside-root/rslib.config.ts
tests/integration/dts/check/outside-root/src/index.ts
tests/integration/dts/check/outside-root/tsconfig.json
tests/integration/dts/check/tsconfig/declarationDir.json
tests/integration/dts/index.test.ts

warn if `declarationDir` or `outDir` is resolved outside project root
#779

feat: warn if `declarationDir` or `outDir` is resolved outside project root

---

packages/plugin-dts/src/index.ts
packages/plugin-dts/src/utils.ts
packages/plugin-dts/tests/dts.test.ts

In https://github.com/web-infra-dev/rslib/pull/780, `outDir` is used to generate dtsEmitPath with a higher priority than `output.distPath.root`. This is an unexpected change, this PR revert it.
close: #785

fix: revert dtsEmitPath generate logic to respect `output.distPath.root`

---

website/docs/en/config/lib/bundle.mdx
website/docs/zh/config/lib/bundle.mdx

enhance entry exclude in bundleless mode
#786

docs: enhance entry exclusion in bundleless mode

---

packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml
tests/integration/dts/__snapshots__/index.test.ts.snap
tests/integration/dts/bundle/multiple-entries/package.json
tests/integration/dts/bundle/multiple-entries/rslib.config.ts
tests/integration/dts/index.test.ts
website/docs/en/config/lib/dts.mdx
website/docs/zh/config/lib/dts.mdx

`@microsoft/api-extractor` only support single entry to bundle DTS, in this PR, we support multiple entries by calling api-extractor multiple times.
close: #738

feat: support bundle DTS of multiple entries

---

website/docs/en/config/lib/external-helpers.mdx
website/docs/zh/config/lib/external-helpers.mdx

Correct `externalHelpers` highlights and update description.

docs: correct `externalHelpers` highlights

---

website/docs/en/config/rsbuild/resolve.mdx
website/docs/zh/config/rsbuild/resolve.mdx

Modify description of `resolve.alias`, and users can click to jump to the Rsbuild documentation for more detailed information.

docs: modify description of `resolve.alias`

---

packages/core/src/types/config.ts
packages/plugin-dts/README.md
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
tests/integration/dts/index.test.ts
website/docs/en/config/lib/banner.mdx
website/docs/en/config/lib/bundle.mdx
website/docs/en/config/lib/dts.mdx
website/docs/en/config/lib/footer.mdx
website/docs/en/config/lib/out-base.mdx
website/docs/en/config/lib/redirect.mdx
website/docs/en/guide/advanced/dts.mdx
website/docs/en/guide/faq/features.mdx
website/docs/en/guide/migration/modernjs-module.mdx
website/docs/en/guide/start/glossary.mdx
website/docs/zh/config/lib/banner.mdx
website/docs/zh/config/lib/dts.mdx
website/docs/zh/config/lib/footer.mdx
website/docs/zh/config/lib/out-base.mdx
website/docs/zh/config/lib/redirect.mdx
website/docs/zh/guide/advanced/dts.mdx
website/docs/zh/guide/faq/features.mdx
website/docs/zh/guide/migration/modernjs-module.mdx
website/docs/zh/guide/start/glossary.mdx

- Replace keyword `DTS` in docs and plugin logs to `declaration files` to make users easier to understand.
- Add `[tsc]` prefix to dts logs to make log sources clearer

refactor: optimize dts logs/docs with `declaration files` keyword

---

packages/core/src/config.ts
tests/integration/auto-extension/index.test.ts
tests/integration/auto-extension/type-commonjs/config-override/rslib.config.ts
tests/integration/auto-extension/type-module/config-override/rslib.config.ts
website/docs/en/config/rsbuild/output.mdx
website/docs/zh/config/rsbuild/output.mdx

By default, Rslib will modify the JavaScript output file extension by setting `output.filename.js`.
We should handle `output.filenameHash` configuration setting by users.

fix: `output.filenameHash` does not take effect on JavaScript files

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/config-check/index.test.ts
tests/integration/config-check/lib-array/package.json
tests/integration/config-check/lib-array/rslib.config.ts

`lib` field is **required** in Rslib, we should check it is a valid array with at least one element.

fix: should check lib array non-empty

---

pnpm-lock.yaml
website/package.json
website/theme/index.tsx

update Rspress to v2.0.0-alpha.1
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-alpha.1

chore(deps): update Rspress to v2.0.0-alpha.1

---

website/docs/en/guide/start/quick-start.mdx
website/theme/index.scss

Align the website theme colors with Rspack.

docs: align theme colors with Rspack

---

tests/integration/style/less/bundle-false/rslib.config.ts
tests/integration/style/less/bundle-import/rslib.config.ts
tests/integration/style/less/bundle/rslib.config.ts
tests/integration/style/postcss/bundle-false/rslib.config.ts
tests/integration/style/postcss/bundle/rslib.config.ts
tests/integration/style/sass/__fixtures__/src/index.scss
tests/integration/style/sass/__snapshots__/index.test.ts.snap
tests/integration/style/sass/bundle-false/rslib.config.ts
tests/integration/style/sass/bundle/rslib.config.ts
tests/integration/style/sass/index.test.ts
tests/integration/style/tailwindcss/bundle-false/postcss.config.cjs
tests/integration/style/tailwindcss/bundle-false/rslib.config.ts
tests/integration/style/tailwindcss/bundle/postcss.config.cjs
tests/integration/style/tailwindcss/bundle/rslib.config.ts
tests/integration/umd/index.test.ts

- remove `root` to avoid warning logs of failed to load `package.json`
- no need to set `lightningcssLoader: false` when using postcss
- resolve `Sass variables aren't allowed in plain CSS` issue in tests
- use `postcss.config.cjs` instead of `postcss.config.ts` to avoid warning in higher Node.js version
- await the assertion to remove unexpected feature which will be removed in Vitest 3.0

test: refactor some style tests

---

package.json
website/docs/en/guide/basic/output-structure.mdx
website/docs/en/guide/faq/features.mdx
website/docs/en/guide/start/glossary.mdx
website/docs/zh/guide/basic/output-structure.mdx
website/docs/zh/guide/start/glossary.mdx

- Modify bundleless definition
- update pnpm to `v10.6.2`

docs: polish bundleless glossary

---

website/docs/en/guide/advanced/dts.mdx
website/docs/zh/guide/advanced/dts.mdx

add some default strategy of declaration files generation.

docs: add some default strategy of declaration files generation

---

packages/core/__mocks__/rslog.cjs
packages/core/src/cli/restart.ts
packages/core/src/config.ts
packages/core/src/utils/extension.ts
packages/core/src/utils/helper.ts
packages/core/src/utils/logger.ts
packages/plugin-dts/src/utils.ts
tests/integration/auto-external/index.test.ts
tests/integration/externals/index.test.ts

- Include several changes to enforce a consistent logging message case convention across the codebase
```js
/**
* Logging message case convention:
*
* Info, ready, success and debug messages:
* - Start with lowercase
* - Example: "info  build started..."
*
* Errors and warnings:
* - Start with uppercase
* - Example: "error  Failed to build"
*
* This convention helps distinguish between normal operations
* and important alerts that require attention.
*/
```
- Use `rslib` as our DEBUG key
- Add issuer path in logs of `module-import-warn` cases

fix: standardize logging messages

---

examples/module-federation/mf-host/package.json
examples/module-federation/mf-remote/package.json
packages/core/package.json
packages/create-rslib/fragments/tools/storybook-react-js/package.json
packages/create-rslib/fragments/tools/storybook-react-ts/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/integration/externals/index.test.ts
tests/package.json
tests/scripts/rsbuild.ts
website/package.json

Update Rsbuild to v1.2.19 and adapt to the error message change, related https://github.com/web-infra-dev/rsbuild/pull/4772
https://github.com/web-infra-dev/rsbuild/releases/tag/v1.2.19

chore(deps): update Rsbuild to v1.2.19

---

packages/core/src/plugins/EntryChunkPlugin.ts
packages/core/tests/__snapshots__/config.test.ts.snap
tests/integration/cli/build-watch/build.test.ts
tests/integration/cli/build-watch/rslib.config.ts

- The `contextDependencies.add()` only works with `.tapPromise` in Rspack now due to a bug, so the hooks name is changed in this PR.
- Changed the test case, to make it failed in previous implementation.

fix: correct use contextDependencies

---

website/theme/index.scss

Apply new theme colors to the documentation site:
- New brand color
- Default code block color of Rspress
- Clean up unused variables
The same as Rspack: https://github.com/web-infra-dev/rspack/pull/9689

docs: apply new theme colors to the documentation site

---

packages/core/src/config.ts
packages/core/src/types/config.ts

Fix inaccurate type descriptions in `RslibConfig` using `@override` annotation
GH-856

fix: override default values of some type descriptions

---

tests/integration/cli/build-watch/build.test.ts
tests/scripts/helper.ts

test: fix unstable build --watch test

---

packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/tsc.ts

- Do not verbose some meaningless logs of api-extractor.
- Add `[api-extractor]` prefix for error when bunding dts files.
- Output relative paths for dts files/source file to reduce length of logs.
- Use `formatDiagnosticsWithColorAndContext` to show codeblocks of tsc diagnostics.
close: https://github.com/web-infra-dev/rslib/issues/631

refactor: optimize dts logs and show codeblocks of tsc diagnostics

---

examples/module-federation/mf-host/package.json
examples/module-federation/mf-remote/package.json
packages/core/package.json
packages/create-rslib/fragments/tools/storybook-react-js/package.json
packages/create-rslib/fragments/tools/storybook-react-ts/package.json
packages/create-rslib/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/package.json
website/package.json

bump Rstack packages:
- Rslib: `0.5.4` -> `0.5.5`
- Rspress: `2.0.0-alpha.3` -> `2.0.0-alpha.4`
- Rsbuild: `1.2.19` -> `1.3.0-beta.0`
- https://github.com/web-infra-dev/rslib/releases/tag/v0.5.5
- https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-alpha.4
- https://github.com/web-infra-dev/rsbuild/releases/tag/v1.3.0-beta.0

chore(deps): bump Rslib/Rspress/Rsbuild

---

tests/integration/style/sass/bundle-false/rslib.config.ts
website/docs/en/config/rsbuild/output.mdx
website/docs/en/guide/advanced/static-assets.mdx
website/docs/zh/config/rsbuild/output.mdx
website/docs/zh/guide/advanced/static-assets.mdx

This pull request includes updates to the documentation and configuration files to improve clarity and consistency in how static assets are handled and referenced.
Documentation updates:
* [`website/docs/en/config/rsbuild/output.mdx`](diffhunk://#diff-27391d698ce4c68d230eb1c8ea44170f82b1b0569d4d354c318d9df8990c36dcL11-R18): Clarified the default values for `output.assetPrefix` based on the `format` and explained the behavior when `output.assetPrefix` is set to `"auto"` or a specific path.
* [`website/docs/en/guide/advanced/static-assets.mdx`](diffhunk://#diff-5775c0f5f9283365977b7677d6f071543b9e85de9cc03be9022c686c2daf57b5L16-R18): Updated terminology from "JS file" to "JavaScript file" and provided a clearer explanation of how static assets are imported and handled in different formats. …

docs: enhance `output.assetPrefix`

---

website/docs/en/guide/advanced/json-files.mdx
website/docs/zh/guide/advanced/json-files.mdx

documents to optimize Yaml and toml file support
#821

docs(json): add documents for YAML and TOML file support

---

README.md

Invalid Discord invite URL, replaced with the one mentioned in rspack as they all should lead to the same server
- https://github.com/web-infra-dev/rspack/blob/main/README.md?plain=1#L46

docs: fix Discord URL

---

examples/module-federation/mf-host/package.json
examples/module-federation/mf-remote/package.json
packages/core/package.json
packages/create-rslib/fragments/tools/storybook-react-js/package.json
packages/create-rslib/fragments/tools/storybook-react-ts/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/integration/decorators/__snapshots__/index.test.ts.snap
tests/integration/minify/index.test.ts
tests/package.json
website/package.json

Update Rsbuild to v1.3.0-beta.2 and fix test snapshots.
https://github.com/web-infra-dev/rsbuild/releases/tag/v1.3.0-beta.2

chore(deps): update Rsbuild to v1.3.0-beta.2

---

packages/core/src/index.ts

Make developers convenient to import `rspack` instance and related Rsbuild public APIs and types in Rslib configuration files.
```ts
import { defineConfig, rsbuild, rspack } from '@rslib/core';
type EnvironmentContext = rsbuild.EnvironmentContext;
const PLUGIN_SWC_NAME = rsbuild.PLUGIN_SWC_NAME;
export default defineConfig({
lib: [
{
format: 'esm',
tools: {
rspack: {
plugins: [new rspack.CircularDependencyRspackPlugin({})],
},
},
},
],
});
```

feat: export Rspack and Rsbuild

---

.github/renovate.json5
biome.json
pnpm-lock.yaml
tests/e2e/react-component/package.json
tests/e2e/react-component/rsbuild.config.ts
tests/integration/umd-globals/index.test.ts
tests/integration/umd-globals/package.json
tests/integration/umd-globals/rslib.config.ts

Add umd output of `react` and `react-dom` to local to avoid using `unpkg` thus avoiding issues with the CDN service that cause unstable test results.

test: use local vendor instead of unpkg for react umd outputs

---

packages/core/src/config.ts
packages/core/src/css/cssConfig.ts
packages/core/src/css/libCssExtractLoader.ts
pnpm-lock.yaml
tests/integration/style/css-modules/__fixtures__/basic/src/button/index.module.scss
tests/integration/style/css-modules/bundle-false-auto-false/package.json
tests/integration/style/css-modules/bundle-false-auto-false/rslib.config.ts
tests/integration/style/css-modules/index.test.ts

Do not modify filename when `cssModules.auto: false`.

fix: do not modify filename when `cssModules.auto: false`

---

packages/plugin-dts/src/utils.ts

Hi! ast-grep author here. Thanks for choosing ast-grep.
This PR optimizes the rule to be more selective so that we can avoid the `O(node * tree_height)`matching behavior.
Local minimal testing result
see ast-grep/ast-grep#1920
close https://github.com/web-infra-dev/rslib/issues/914

perf: use more performant ast-grep rule

---

examples/module-federation/mf-react-component/.storybook/main.ts

Previous write-up will break in node23 (https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require). Use the correct write-up.

fix(examples): correct use require in ESM

---

.github/renovate.json5

This pull request updates the Renovate configuration to refine dependency grouping and update behavior. The most important change is the renaming and expansion of the "all patch dependencies" group to include minor updates as well.
* [`.github/renovate.json5`](diffhunk://#diff-20ab1190d08a53a3012bc191ed56205c8f0ffb8fa1715e9d36ecfd1d2ea8a790L51-R54): Renamed the `groupName` from "all patch dependencies" to "non-major dependencies" and updated the `groupSlug` to `non-major`. Additionally, expanded the `matchUpdateTypes` to include both `patch` and `minor` updates instead of just `patch`.

chore(renovate): update non-major dependencies together

---

packages/plugin-dts/src/utils.ts
pnpm-lock.yaml
tests/integration/dts/bundle/no-entry/package.json
tests/integration/dts/bundle/no-entry/rslib.config.ts
tests/integration/dts/index.test.ts

should throw error when no entry find with bundle dts
When users apply bundleless js but need a bundle dts in an object, we can not deal with this.
`dts.only` should be a solution for this case.

fix: should throw error when no entry find with bundle dts

---

packages/plugin-dts/src/utils.ts
tests/integration/redirect/dts.test.ts
tests/integration/redirect/dts/rslib.config.ts

We should only process dts files of current format, this usally happen on multiple dts builds together in the same dist folder.
This should be a regression after #933

fix: should process correct format of dts files

---

packages/plugin-dts/src/utils.ts
tests/integration/redirect/dts.test.ts
tests/integration/redirect/dts/rslib.config.ts
tests/integration/redirect/dts/src/index.ts
tests/integration/redirect/dts/src/types.ts
tests/integration/redirect/dts/tsconfig.json

This PR fix some cases about `redirect.dts.extension`:
1. When path is not redirected to a absolute/relative path (maybe `redirect.dts.path: false` is set), we should not add extension.
2. When path is redirected to `./`, we should remove the `/` prefix first
3. When path is redirected to entry of itself via `paths` in `tsconfig.json`, we should get correct value of `isOutsideRootdir` to make the path redirect to correct relative path from root.

fix: dts redirect extension should add correctly

---

packages/plugin-dts/src/utils.ts
tests/integration/redirect/dts.test.ts
tests/integration/redirect/dts/src/index.ts

We should redirect import_require_clause statement in dts like below:
```ts
import sources = require("webpack-sources");
```
https://github.com/web-infra-dev/rspack/actions/runs/14593020719/job/40933824746

fix: should redirect import_require_clause statement in dts

---

packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
pnpm-lock.yaml
tests/integration/worker/index.test.ts
tests/integration/worker/package.json
tests/integration/worker/rslib.config.ts
tests/integration/worker/src/index.ts
tests/integration/worker/src/worker.ts

Preserve worker syntax, do not transform to Rspack runtime based output.
https://github.com/web-infra-dev/rslib/issues/929

fix: preserve worker syntax

---

pnpm-lock.yaml
tests/integration/json/index.test.ts
tests/integration/json/package.json
tests/integration/json/rslib.config.ts
tests/integration/json/src/foo.json
tests/integration/json/src/index.ts
tests/integration/json/tsconfig.json
website/docs/en/guide/advanced/json-files.mdx
website/docs/zh/guide/advanced/json-files.mdx

The initial motivation of the documentation here was from an internal oncall that the user's JSON be like `{"3rd": 1}` which could not convert to a JS file (variable can't start with a number char), so preserving JSON is the workaround.

docs(JSON): add output relationship with bundle mode

---

website/docs/en/guide/advanced/json-files.mdx
website/docs/zh/guide/advanced/json-files.mdx

docs(json): fix line highlighting

---

.vscode/settings.json
biome.json
pnpm-lock.yaml
scripts/dictionary.txt
tests/e2e/react-component/index.pw.test.ts
website/docs/en/config/lib/dts.mdx
website/docs/en/config/lib/external-helpers.mdx
website/docs/en/config/lib/umd-name.mdx
website/docs/en/guide/advanced/json-files.mdx
website/docs/en/guide/advanced/module-federation.mdx
website/docs/en/guide/advanced/output-compatibility.mdx
website/docs/en/guide/basic/output-format.mdx
website/docs/en/guide/solution/react.mdx
website/docs/zh/config/lib/dts.mdx
website/docs/zh/config/lib/external-helpers.mdx
website/docs/zh/config/lib/umd-name.mdx
website/docs/zh/guide/advanced/json-files.mdx
website/docs/zh/guide/advanced/module-federation.mdx
website/docs/zh/guide/advanced/output-compatibility.mdx
website/docs/zh/guide/basic/output-format.mdx
website/docs/zh/guide/solution/react.mdx
website/package.json
website/rspress.config.ts
website/theme/components/RsbuildDocBadge.tsx

https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.5

docs(deps): upgrade rspress 2.0.0-beta.5

---

packages/core/src/config.ts
packages/core/src/types/config.ts
pnpm-lock.yaml
tests/integration/format/cjs-static-export/package.json
tests/integration/format/default/package.json
tests/integration/format/default/rslib.config.ts
tests/integration/format/default/src/foo.js
tests/integration/format/default/src/index.js
tests/integration/format/import-meta-url/package.json
tests/integration/format/index.test.ts
tests/integration/minify/index.test.ts
tests/scripts/shared.ts
website/docs/en/config/lib/format.mdx
website/docs/zh/config/lib/format.mdx

In this PR, `lib.format` is default from `undefined` to `'esm'` to simplify user configuration and encourage the use of pure esm package.

feat: format default to `'esm'`

---

tests/integration/cli/build-watch/build.test.ts
tests/integration/dts/index.test.ts
tests/integration/externals/index.test.ts
tests/integration/redirect/dts.test.ts
tests/scripts/shared.ts

1. Do not print file size when running tests.
2. Use `proxyConsole` to hide some logs in main process.

test: optimize test logs

---

packages/core/src/config.ts
pnpm-lock.yaml
tests/integration/format/index.test.ts
tests/integration/format/mf-bundle-false/package.json
tests/integration/format/mf-bundle-false/rslib.config.ts
tests/integration/format/mf-bundle-false/src/index.js

We should throw error when using mf format with bundleless mode.

chore: throw error when using bundleless mode with mf format

---

packages/create-rslib/fragments/base/node-dual-js/rslib.config.mjs
packages/create-rslib/fragments/base/node-dual-ts/rslib.config.ts
packages/create-rslib/fragments/base/node-esm-js/rslib.config.mjs
packages/create-rslib/fragments/base/node-esm-ts/rslib.config.ts
packages/create-rslib/template-[node-dual]-[]-js/rslib.config.mjs
packages/create-rslib/template-[node-dual]-[]-ts/rslib.config.ts
packages/create-rslib/template-[node-dual]-[vitest]-js/rslib.config.mjs
packages/create-rslib/template-[node-dual]-[vitest]-ts/rslib.config.ts
packages/create-rslib/template-[node-esm]-[]-js/rslib.config.mjs
packages/create-rslib/template-[node-esm]-[]-ts/rslib.config.ts
packages/create-rslib/template-[node-esm]-[vitest]-js/rslib.config.mjs
packages/create-rslib/template-[node-esm]-[vitest]-ts/rslib.config.ts

Set `syntax` to `esnext` in `create-rslib` to align with the default value we set.

feat(create-rslib): syntax default to esnext

---

packages/create-rslib/fragments/base/node-dual-js/rslib.config.mjs
packages/create-rslib/fragments/base/node-dual-ts/rslib.config.ts
packages/create-rslib/fragments/base/node-esm-js/rslib.config.mjs
packages/create-rslib/fragments/base/node-esm-ts/rslib.config.ts
packages/create-rslib/template-[node-dual]-[]-js/rslib.config.mjs
packages/create-rslib/template-[node-dual]-[]-ts/rslib.config.ts
packages/create-rslib/template-[node-dual]-[vitest]-js/rslib.config.mjs
packages/create-rslib/template-[node-dual]-[vitest]-ts/rslib.config.ts
packages/create-rslib/template-[node-esm]-[]-js/rslib.config.mjs
packages/create-rslib/template-[node-esm]-[]-ts/rslib.config.ts
packages/create-rslib/template-[node-esm]-[vitest]-js/rslib.config.mjs
packages/create-rslib/template-[node-esm]-[vitest]-ts/rslib.config.ts

See https://github.com/web-infra-dev/rslib/pull/982#issuecomment-2876010743, in template, we need to align with usage in most sceniros, so we default syntax to browserlist `['node 18']`.

feat(create-rslib): syntax default to node 18

---

packages/core/src/config.ts
packages/core/src/types/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
packages/core/tests/config.test.ts
pnpm-lock.yaml
tests/integration/format/default/rslib.config.ts
tests/integration/iife/index.test.ts
tests/integration/iife/package.json
tests/integration/iife/rslib.config.ts
tests/integration/iife/rslibBundleFalse.config.ts
tests/integration/iife/src/index.ts
tests/integration/iife/src/utils.ts
tests/scripts/shared.ts
website/docs/en/config/lib/format.mdx
website/docs/en/guide/basic/output-format.mdx
website/docs/zh/config/lib/format.mdx
website/docs/zh/guide/basic/output-format.mdx

feat: support `iife` format

---

README.md
README.zh-CN.md
pnpm-lock.yaml
scripts/dictionary.txt
website/docs/en/guide/start/index.mdx
website/docs/zh/guide/start/index.mdx
website/package.json

This PR adds a new "Rstack" section to the README files , which details the projects of the Rstack toolchain and helps users to understand its concepts and goals.
Same as https://github.com/web-infra-dev/rspack/pull/10424

docs: update Rstack introduction

---

website/docs/en/config/rsbuild/source.mdx
website/docs/zh/config/rsbuild/source.mdx

This pull request updates the documentation for the `source.exclude` configuration in both English and Chinese to provide more clarity and additional guidance. The changes include a detailed explanation of how excluded files are handled and alternative methods for excluding files from the output.
Documentation updates:
* [`website/docs/en/config/rsbuild/source.mdx`](diffhunk://#diff-1f8928b3b498e56bd57bfb986458699df0a4be504e487364d3a0e355010c7579L51-R62): Enhanced the description of `source.exclude` to clarify that excluded files are not translated by SWC but are still bundled into the output. Added a note with methods to prevent files from being bundled, including using Rspack's `IgnorePlugin` in bundle mode or configuring `source.entry` in bundleless mode.
* …

docs: optimize `source.exclude` description

---

website/docs/en/config/rsbuild/source.mdx
website/docs/en/guide/faq/features.mdx
website/docs/zh/config/rsbuild/source.mdx
website/docs/zh/guide/faq/features.mdx
website/rspress.config.ts

This pull request introduces several documentation updates and a minor configuration enhancement. The documentation changes improve clarity and add new examples for preserving module variables during builds, while the configuration update adds a new transformer for handling notation diffs in markdown processing.
* Updated the description of `source.define` in both English (`website/docs/en/config/rsbuild/source.mdx`) and Chinese (`website/docs/zh/config/rsbuild/source.mdx`) to highlight its use for injecting environment variables during build time. [[1]](diffhunk://#diff-1f8928b3b498e56bd57bfb986458699df0a4be504e487364d3a0e355010c7579L20-R20) [[2]](diffhunk://#diff-22bc930e740adffeae317d5fad8e524ce56e4e04a87a2b2b65a350abb8f7a24eL19-R19)
* Added a new FAQ section in both English …

docs: add how to preserve module variables

---

website/docs/en/guide/basic/cli.mdx
website/docs/zh/guide/basic/cli.mdx

docs: optimize cli docs

---

website/docs/en/config/rsbuild/plugins.mdx
website/docs/zh/config/rsbuild/plugins.mdx

update plugins bundleless compatibility

docs: update plugins bundleless compatibility

---

.github/renovate.json5

Allow to update `@types/node` and non-patch `pnpm` version.
This pull request updates the `.github/renovate.json5` file to improve package grouping and dependency management. Key changes include standardizing naming conventions for package groups, modifying match patterns for better accuracy, and revising the handling of specific dependencies.
* Updated group names to use consistent capitalization (e.g., `Babel`, `Rsbuild`, `Rspress`) and replaced wildcard match patterns with regex patterns for better precision.
* Renamed the `modern-js` group to `Module Federation` and updated its match pattern to align with the new naming convention.
* Added a new configuration to disable patch updates for the `pnpm` package by specifying it in the `matchPackageNames` and `matchUpdateTypes` fields.
* …

chore(renovate): update Renovate configuration

---

packages/core/src/config.ts
packages/core/src/types/config.ts
tests/integration/umd-library-name/index.test.ts
tests/integration/umd-library-name/rslib.config.ts
website/docs/en/config/lib/index.mdx
website/docs/en/config/lib/umd-name.mdx
website/docs/zh/config/lib/index.mdx
website/docs/zh/config/lib/umd-name.mdx

support `umdName` of array and object type to keep align with `Rspack.LibraryName`.
close: #1017

feat: support `umdName` of array and object type

---

examples/module-federation/mf-host/package.json
examples/module-federation/mf-remote/package.json
packages/core/package.json
packages/create-rslib/fragments/tools/storybook-react-js/package.json
packages/create-rslib/fragments/tools/storybook-react-ts/package.json
packages/create-rslib/fragments/tools/storybook-vue-js/package.json
packages/create-rslib/fragments/tools/storybook-vue-ts/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/create-rslib/template-[vue]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[vue]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[vue]-[storybook]-js/package.json
packages/create-rslib/template-[vue]-[storybook]-ts/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/package.json
website/package.json

Change `@rsbuild/core` from caret (^) to tilde (~) range in storybook template to ensure users only automatically accept patch-level updates to prevent potential minor version breaking changes causing by SWC.

chore(deps): change @rsbuild/core from caret (^) to tilde (~) range

---

website/docs/public/netlify.toml

Redirect lib.rsbuild.dev to rslib.rs to ensure that users access the same domain name.
See: https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects

docs: redirect lib.rsbuild.dev to rslib.rs

---

website/docs/public/netlify.toml

Disable domain redirection as DNS records need time to propagate (spread) across DNS servers worldwide. 
https://www.whatsmydns.net/#NS/rslib.rs

docs: disable domain redirection

---

website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/start/quick-start.mdx

update Vue template in quick start chapter

docs: update Vue template in quick start chapter

---

packages/core/src/types/config.ts
packages/plugin-dts/README.md
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/tests/external.test.ts
pnpm-lock.yaml
tests/integration/dts/bundle/bundled-packages/package.json
tests/integration/dts/bundle/bundled-packages/rslib.config.ts
tests/integration/dts/bundle/bundled-packages/src/index.ts
tests/integration/dts/bundle/bundled-packages/tsconfig.json
tests/integration/dts/index.test.ts
website/docs/en/config/lib/dts.mdx
website/docs/zh/config/lib/dts.mdx

support override `bundledPackages` to `@microsoft/api-extractor`.

feat(dts): support override bundledPackages

---

website/docs/en/guide/basic/output-format.mdx
website/docs/zh/guide/basic/output-format.mdx

Updates the description for the output formats to include IIFE.

docs: update output format description to include IIFE

---

website/docs/public/netlify.toml

background: https://github.com/web-infra-dev/rslib/pull/1030
Several time has passed, the global propagation of dns should be ready. 
Reopen redirection from `lib.rsbuild.dev` to `rslib.rs` again.

docs: reopen domain redirection

---

pnpm-lock.yaml
website/package.json

style breaking changes in `2.0.0-beta.10`.

chore(deps): revert rspress 2.0.0-beta.10

---

pnpm-lock.yaml
website/package.json
website/rspress.config.ts

Integrate the `rspress-plugin-sitemap` to generate the sitemap for SEO.

docs: generate the sitemap for SEO

---

tests/integration/resolve/false/rslib.config.ts

This test case is skipped since https://github.com/web-infra-dev/rslib/issues/149, but since we modify default target to `'node'` formly, we should manually set `'web'` in this case.

test: correct test config of resolve false case

---

website/docs/en/guide/faq/features.mdx
website/docs/zh/guide/faq/features.mdx

add difference of modify config plugin hook
close: #1037

docs: add difference of modify config plugin hook

---

packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
tests/integration/dts/index.test.ts

remove error stack which is not helpful to users.

chore(plugin-dts): remove error stack which is not helpful to users

---

website/docs/en/guide/advanced/output-compatibility.mdx
website/docs/zh/guide/advanced/output-compatibility.mdx

clarify how to set browserslist
close: #1004

docs: clarify how to set browserslist

---

website/docs/en/guide/advanced/dts.mdx
website/docs/zh/config/lib/dts.mdx
website/docs/zh/guide/advanced/dts.mdx

docs: list a table of all dts features
close: #1052

docs: list a table of all dts features

---

tests/integration/dts/index.test.ts

do not display error logs in terminal during testing to avoid affecting the judgment of CI results when CI failed.

test: do not display expected error logs in terminal during testing

---

packages/core/src/css/cssConfig.ts
pnpm-lock.yaml
tests/integration/redirect/js.test.ts
tests/integration/redirect/js/package.json
tests/integration/redirect/js/src/index.ts
tests/integration/redirect/style.test.ts
tests/integration/redirect/style/.gitignore
tests/integration/redirect/style/node_modules/third-party/index.module.scss
tests/integration/redirect/style/node_modules/third-party/package.json
tests/integration/redirect/style/src/pkg/index.ts

Do not redirect third party css, use same strategy with js redirect.
fix: #1066

fix: do not redirect third party css file

---

website/docs/en/guide/advanced/json-files.mdx
website/docs/zh/guide/advanced/json-files.mdx

Add chapter of using import attributes to import JSON files.
close: https://github.com/web-infra-dev/rslib/issues/1076

docs: use import attributes to import JSON files

---

packages/plugin-dts/src/tsc.ts

Since `createIncrementalProgram` does not have a `getPreEmitDiagnostics` method, merge all kinds of diagnostics by api.
wrong modify in  https://github.com/web-infra-dev/rslib/pull/1081

fix(dts): collect all kinds of diagnostics when composite is true

---

examples/module-federation/mf-host/package.json
examples/module-federation/mf-remote/package.json
packages/core/package.json
packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
packages/create-rslib/fragments/tools/storybook-react-js/package.json
packages/create-rslib/fragments/tools/storybook-react-ts/package.json
packages/create-rslib/fragments/tools/storybook-vue-js/package.json
packages/create-rslib/fragments/tools/storybook-vue-ts/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/create-rslib/template-[vue]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[vue]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[vue]-[storybook]-js/package.json
packages/create-rslib/template-[vue]-[storybook]-ts/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/package.json
tests/scripts/rsbuild.ts
website/package.json

- bump Rsbuild 1.4.0-rc.0
- `dev.progressBar` now default to `false` in Rsbuild, remove configurations in Rslib
https://github.com/web-infra-dev/rsbuild/releases/tag/v1.4.0-rc.0

chore(deps): bump Rsbuild 1.4.0-rc.0

---

examples/module-federation/mf-host/package.json
examples/module-federation/mf-remote/package.json
packages/core/package.json
packages/create-rslib/fragments/tools/storybook-react-js/package.json
packages/create-rslib/fragments/tools/storybook-react-ts/package.json
packages/create-rslib/fragments/tools/storybook-vue-js/package.json
packages/create-rslib/fragments/tools/storybook-vue-ts/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/create-rslib/template-[vue]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[vue]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[vue]-[storybook]-js/package.json
packages/create-rslib/template-[vue]-[storybook]-ts/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/package.json
website/package.json

This error message is not easy to understand
```txt
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have mgm
Location: crates/rspack_plugin_library/src/modern_module_library_plugin.rs:288
```
ship changes in https://github.com/web-infra-dev/rspack/pull/10930 to enhance this

chore(deps): bump Rsbuild 1.4.5

---

packages/plugin-dts/src/utils.ts
tests/integration/redirect/dts.test.ts
tests/integration/redirect/dts/src/index.ts
tests/integration/redirect/dts/tsconfig.json

Usually developers will unify the versions of related types and solve the problem of multiple instances by writing the following in the `paths` of `tsconfig.json`. In this case, we do not need to redirect it to `../node_modules/foo`, just keep the original request.
```json
{
"compilerOptions": {
"paths": {
"foo": ["./node_modules/foo"],
"bar": ["./node_modules/@types/bar"],
}
},
}
```

fix(dts): preserve importer if resolved to node_modules folder

---

packages/core/package.json
packages/create-rslib/package.json
packages/plugin-dts/package.json

Boolean values are no longer supported for `redirect.asset`, see the documentation of [redirect.asset](https://lib.rsbuild.dev/config/lib/redirect#redirectasset) for more details. ([#1119](https://github.com/web-infra-dev/rslib/pull/1119))
Please note the following changes that may require adjustments to your configurations:
```diff
export default defineConfig({
lib: [
{
redirect: {
-        asset: true,
+        asset: {
+          path: true,
+          extension: true,
+        },
},
},
],
});
```
```diff
export default defineConfig({
lib: [
{
redirect: {
-        asset: false,
+        asset: {
+          path: false,
+          extension: false,
+        },
},
},
],
});
```

Release v0.11.0

---

examples/module-federation/mf-host/package.json
examples/module-federation/mf-remote/package.json
packages/core/package.json
packages/create-rslib/fragments/tools/storybook-react-js/package.json
packages/create-rslib/fragments/tools/storybook-react-ts/package.json
packages/create-rslib/fragments/tools/storybook-vue-js/package.json
packages/create-rslib/fragments/tools/storybook-vue-ts/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[react]-[storybook]-js/package.json
packages/create-rslib/template-[react]-[storybook]-ts/package.json
packages/create-rslib/template-[vue]-[storybook,vitest]-js/package.json
packages/create-rslib/template-[vue]-[storybook,vitest]-ts/package.json
packages/create-rslib/template-[vue]-[storybook]-js/package.json
packages/create-rslib/template-[vue]-[storybook]-ts/package.json
packages/plugin-dts/package.json
pnpm-lock.yaml
tests/package.json
website/package.json

This PR brings some import changes:
fix PR: https://github.com/web-infra-dev/rspack/pull/11229
close: #882
close: #1007 
support PR: https://github.com/web-infra-dev/rspack/pull/11218
close: https://github.com/web-infra-dev/rslib/discussions/1131
Users can modify minify configurations to set `comments: 'all'` to keep magic comments in output.
see https://rslib.rs/config/rsbuild/output#outputminify
e.g.
```diff
export default defineConfig({
output: {
minify: {
js: true,
css: false,
jsOptions: {
minimizerOptions: {
mangle: false,
minify: false,
compress: {
defaults: false,
unused: true,
dead_code: true,
toplevel: true,
},
format: {
-           comments: 'some',
+           comments: 'all',
preserve_annotations: true,
},
},
},
},
},
});
```

chore(deps): bump Rsbuild 1.4.12

---

website/theme/index.tsx

docs: add llms copy button

---

.github/workflows/release.yml
packages/core/package.json
packages/create-rslib/package.json
packages/plugin-dts/package.json

Enable OIDC publishing to make it easier and more secure to publish npm packages from CI.
- https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
- https://docs.npmjs.com/trusted-publishers

chore: enable trusted publishing for npm packages

---

README.md
README.zh-CN.md
biome.json
package.json
packages/core/src/cli/prepare.ts
packages/core/src/config.ts
packages/core/src/css/cssConfig.ts
packages/core/src/css/libCssExtractLoader.ts
packages/core/src/utils/helper.ts
packages/core/src/utils/logger.ts
packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/dts.ts
packages/plugin-dts/src/index.ts
packages/plugin-dts/src/tsc.ts
packages/plugin-dts/src/utils.ts
pnpm-lock.yaml
rslint.jsonc
scripts/dictionary.txt
website/docs/en/guide/start/index.mdx
website/docs/zh/guide/start/index.mdx

[Rslint](https://github.com/web-infra-dev/rslint) yes.

chore: integrate Rslint for type-aware linting

---

README.md
README.zh-CN.md
website/docs/en/guide/start/index.mdx
website/docs/zh/guide/start/index.mdx

Add version badges to the Rstack tools table, this should help users understand the current status and latest version number of each project.

docs: add version badges to Rstack tools table

---

tests/integration/cli/build-watch/build.test.ts
tests/integration/cli/mf/mf.test.ts
tests/integration/plugins/index.test.ts
tests/integration/server/index.test.ts
tests/scripts/helper.ts

There exists flaky test cases about watching files changed.

test: use `expect.poll` to avoid flaky watching file changes test cases

---

package.json
packages/core/package.json
packages/create-rslib/package.json
packages/plugin-dts/package.json
website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/start/quick-start.mdx

Rspack and Rsbuild v1.5 will no longer support Node 16, as Node.js reached end-of-life on September 11th, 2023, and many npm packages in the ecosystem have also dropped support for Node 16.
This PR update the engines field in `package.json` to require Node.js >= 18.12.0.
https://github.com/web-infra-dev/rspack/discussions/10867

feat!: update minimum Node.js version to 18.12.0

---

examples/module-federation/mf-host/tsconfig.json
examples/module-federation/mf-remote/tsconfig.json
examples/vue-component-bundle/tsconfig.json
examples/vue-component-bundleless/tsconfig.json
packages/core/rslib.config.ts
packages/create-rslib/fragments/base/node-dual-ts/tsconfig.json
packages/create-rslib/fragments/base/node-esm-ts/tsconfig.json
packages/create-rslib/fragments/base/react-ts/tsconfig.json
packages/create-rslib/fragments/base/vue-ts/tsconfig.json
packages/create-rslib/rslib.config.ts
packages/create-rslib/template-[node-dual]-[]-ts/tsconfig.json
packages/create-rslib/template-[node-dual]-[vitest]-ts/tsconfig.json
packages/create-rslib/template-[node-esm]-[]-ts/tsconfig.json
packages/create-rslib/template-[node-esm]-[vitest]-ts/tsconfig.json
packages/create-rslib/template-[react]-[]-ts/tsconfig.json
packages/create-rslib/template-[react]-[storybook,vitest]-ts/tsconfig.json
packages/create-rslib/template-[react]-[storybook]-ts/tsconfig.json
packages/create-rslib/template-[react]-[vitest]-ts/tsconfig.json
packages/create-rslib/template-[vue]-[]-ts/tsconfig.json
packages/create-rslib/template-[vue]-[storybook,vitest]-ts/tsconfig.json
packages/create-rslib/template-[vue]-[storybook]-ts/tsconfig.json
packages/create-rslib/template-[vue]-[vitest]-ts/tsconfig.json
packages/plugin-dts/rslib.config.ts
scripts/tsconfig/base.json
tests/e2e/react-component/tsconfig.json

Since Rstack no longer supports Node 16, we can update build configs to lib ES2022.

feat: update tsconfig.json and build configs to ES2022

---

packages/plugin-dts/src/tsc.ts
pnpm-lock.yaml
tests/integration/dts/build/declaration-map/package.json
tests/integration/dts/build/declaration-map/rslib.config.ts
tests/integration/dts/build/declaration-map/src/index.ts
tests/integration/dts/build/declaration-map/tsconfig.cjs.json
tests/integration/dts/build/declaration-map/tsconfig.esm.json
tests/integration/dts/bundle-false/declaration-map/package.json
tests/integration/dts/bundle-false/declaration-map/rslib.config.ts
tests/integration/dts/bundle-false/declaration-map/src/index.ts
tests/integration/dts/bundle-false/declaration-map/tsconfig.json
tests/integration/dts/composite/declaration-map/package.json
tests/integration/dts/composite/declaration-map/rslib.config.ts
tests/integration/dts/composite/declaration-map/src/index.ts
tests/integration/dts/composite/declaration-map/tsconfig.json
tests/integration/dts/index.test.ts

Support emitting `.d.cts.map` and `.d.mts.map` files。
- declaration maps file names
- declaration maps `file` field corresonding to source file name
- declaration file mapping url links

feat(dts): support emitting `.d.cts.map` and `.d.mts.map` files

---

packages/core/src/css/cssConfig.ts
pnpm-lock.yaml

`const rule = config.module.rule(ruleId);` will add an empty rule like below:
```
/* config.module.rule('sass') */
{},
/* config.module.rule('less') */
{},
/* config.module.rule('stylus') */
{},
```
When `@rsbuild/plugin-sass` begin to modify configurations, a unique id will be generated for Sass rules:
```
/* config.module.rule('sass-1') */
{},
```
Other plugins like [rsbuild-plugin-typed-css-modules](https://github.com/rspack-contrib/rsbuild-plugin-typed-css-modules) rely on `CHAIN_ID.RULE.SASS` to match rules to make features work, see https://github.com/web-infra-dev/rsbuild/issues/5909.

fix(css): prevent adding empty css rule

---

packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap

sync chunk of umd can not be loaded without mounting on scripts

feat: only split async chunks for umd format

---

packages/core/src/config.ts
tests/integration/bundle-false/basic/src/.hidden-folder/index.ts
tests/integration/bundle-false/basic/src/.hidden.ts
tests/integration/bundle-false/basic/src/index.ts
tests/integration/bundle-false/index.test.ts
tests/integration/redirect/dts.test.ts
tests/integration/redirect/dts/src/.hidden-folder/index.ts
tests/integration/redirect/dts/src/.hidden.ts
tests/integration/redirect/dts/src/index.ts
tests/integration/redirect/js.test.ts
tests/integration/redirect/js/src/.hidden-folder/index.ts
tests/integration/redirect/js/src/.hidden.ts
tests/integration/redirect/js/src/index.ts
tests/scripts/helper.ts
tests/scripts/shared.ts

Add an option to prevent glob from ignoring directories starting with a dot.
close #1195

fix: should glob dot files in bundleless mode

---

packages/plugin-dts/src/apiExtractor.ts
packages/plugin-dts/src/index.ts

Enhance error logs for dts `mainEntryPointFilePath` not found.

chore(dts): enhance error logs for dts mainEntryPointFilePath not found

---

.github/workflows/test.yml
.vscode/extensions.json
.vscode/settings.json
packages/core/package.json
packages/core/rslib.config.ts
packages/core/tsconfig.json
packages/create-rslib/package.json
packages/plugin-dts/package.json
packages/plugin-dts/rslib.config.ts
packages/plugin-dts/tsconfig.json
pnpm-lock.yaml

Use tsgo to generate dts in local.
https://github.com/web-infra-dev/rslib/releases/tag/v0.13.0

chore: bump Rslib and enable tsgo in local

---

packages/plugin-dts/README.md
website/docs/en/config/lib/dts.mdx
website/docs/zh/config/lib/dts.mdx

add hint for whether to enable `dts.build`

docs: add hint for whether to enable `dts.build`

---

packages/core/src/config.ts
packages/core/tests/__snapshots__/config.test.ts.snap
pnpm-lock.yaml
tests/integration/output/chunkFileName-multi/package.json
tests/integration/output/chunkFileName-multi/rslib1.config.ts
tests/integration/output/chunkFileName-multi/rslib2.config.ts
tests/integration/output/chunkFileName-multi/rslib3.config.ts
tests/integration/output/chunkFileName-multi/src/lib1.js
tests/integration/output/chunkFileName-multi/src/lib2.js
tests/integration/output/chunkFileName-multi/src/shared.js
tests/integration/output/chunkFileName-single/package.json
tests/integration/output/chunkFileName-single/rslib.config.ts
tests/integration/output/chunkFileName-single/src/lib1.js
tests/integration/output/chunkFileName-single/src/shared.js
tests/integration/output/index.test.ts

to fix the case added in test cases, multi-compiler don't know other compilers' existence, so it's prone to emit chunk file to same path, whereas the content might not the same. this it's not prone to happen in Rsbuild as the hash is enabled but hash is disabled in Rslib.

fix: avoid chunk conflicts when multiple libs are present

---

.github/renovate.json5

Ignore `jsdom` due to Node.js version limit
https://github.com/jsdom/jsdom/blob/HEAD/Changelog.md#2700

chore(renovate): ignore `jsdom` due to Node.js version limit

---

website/theme/components/RsbuildDocBadge.tsx

fix(docs): use `rp-not-doc` for rsbuild doc badge

---

website/docs/en/guide/advanced/module-federation.mdx
website/docs/en/guide/advanced/storybook.mdx
website/docs/en/guide/solution/index.mdx
website/docs/en/guide/solution/nodejs.mdx
website/docs/en/guide/solution/react.mdx
website/docs/en/guide/solution/vue.mdx
website/docs/zh/guide/advanced/module-federation.mdx
website/docs/zh/guide/advanced/storybook.mdx
website/docs/zh/guide/solution/index.mdx
website/docs/zh/guide/solution/nodejs.mdx
website/docs/zh/guide/solution/react.mdx
website/docs/zh/guide/solution/vue.mdx

update examples link to [rstack-examples](https://github.com/rspack-contrib/rstack-examples/tree/main)

docs: update examples link
