- README.md
> fix: typo wrong in README

- packages/plugin-dts/src/tsc.ts
- packages/plugin-dts/src/utils.ts
> chore: optimize dts error log

- CONTRIBUTING.md
- package.json
- packages/core/src/config.ts
- packages/core/tests/__snapshots__/config.test.ts.snap
- pnpm-lock.yaml
"module-import" landed in https://github.com/web-infra-dev/rspack/pull/7479.
> feat: use "module-import" in ESM

- .changeset/rotten-ducks-learn.md
> chore: add 0.0.1 changeset

- package.json
> chore: add changeset script

- README.md
update readme with npm packages and contributors
> docs: update readme with npm packages and contributors

- .github/workflows/lint.yml
- package.json
- pnpm-lock.yaml
> chore: add pnpm dedupe check

- packages/core/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
> chore: bump Rslib 0.0.2

- packages/plugin-dts/src/dts.ts
- packages/plugin-dts/src/tsc.ts
- packages/plugin-dts/src/utils.ts
Use default export of the typescript package.
Older versions (prior to 5.5) of the TypeScript package export APIs with default export only.
Sample:
```text
┌─────────┬────────────────────────────────┬──────────────────────────────────────────┬──────────────────────────────────────────┐
│ (index) │ api                            │ Named Export                             │ Default Export                           │
├─────────┼────────────────────────────────┼──────────────────────────────────────────┼──────────────────────────────────────────┤
│ 0       │ 'versionMajorMinor'            │ '5.5'                                    │ '5.5'                                    │
│ 1       │ 'findConfigFile'               │ [Function: findConfigFile]               │ [Function: findConfigFile] …
```
> fix(plugin-dts): undefined named export from typescript package

- e2e/cases/auto-extension/index.test.ts
- e2e/cases/auto-extension/type-commonjs/config-override/package.json
- e2e/cases/auto-extension/type-commonjs/config-override/rslib.config.ts
- e2e/cases/auto-extension/type-module/config-override/package.json
- e2e/cases/auto-extension/type-module/config-override/rslib.config.ts
- packages/core/src/config.ts
> fix: should respect `output.filename.js` config

- packages/plugin-dts/src/apiExtractor.ts
- packages/plugin-dts/src/dts.ts
- packages/plugin-dts/src/utils.ts
> fix(type): import type from 'src'

- packages/core/src/utils/extension.ts
> fix(types): import 'src' in core

- e2e/package.json
- examples/express-plugin/rslib.config.ts
- examples/react-component/rslib.config.ts
- packages/core/package.json
- packages/core/rslib.config.ts
- packages/plugin-dts/package.json
- pnpm-lock.yaml
bump `@rsbuild/core` to `1.0.1-beta.15`
> chore: bump @rsbuild/core

- .github/workflows/bench-pr.yml
> chore: add bench-pr.yml

- README.md
> docs: add QoS to README

- e2e/cases/dts/bundle/absolute-entry/package.json
- e2e/cases/dts/bundle/absolute-entry/rslib.config.ts
- e2e/cases/dts/index.test.ts
- packages/plugin-dts/src/dts.ts
absolute entry when bundle DTS
> fix: absolute entry when bundle DTS

- .github/pr-labeler.yml
- .github/release.yml
> chore: modify release.yml

- CONTRIBUTING.md
- package.json
- packages/core/package.json
- packages/core/rslib.config.ts
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- bump `@rslib/core` to `0.0.3`
- bump `@microsoft/api-extractor` to `7.47.7`
> chore: bump Rslib

- packages/core/src/config.ts
- packages/core/tests/__snapshots__/config.test.ts.snap
do not need to `mergeRsbuildConfig` twice
> refactor: merge user config

- packages/core/src/config.ts
- packages/core/src/utils/helper.ts
- packages/core/tests/__snapshots__/config.test.ts.snap
not pass lib config in mergeRsbuildConfig
> chore: omit lib config before mergeRsbuildConfig

- CONTRIBUTING.md
- e2e/cases/alias/__snapshots__/index.test.ts.snap
- e2e/cases/auto-extension/index.test.ts
- e2e/cases/extension-alias/__snapshots__/index.test.ts.snap
- e2e/cases/minify/default/rslib.config.ts
- e2e/cases/minify/default/src/index.ts
- e2e/cases/minify/index.test.ts
- e2e/cases/shims/esm/src/index.ts
- e2e/cases/shims/index.test.ts
- e2e/cases/syntax/__snapshots__/index.test.ts.snap
- package.json
- packages/core/src/config.ts
- packages/core/tests/__snapshots__/config.test.ts.snap
- pnpm-lock.yaml
Add default minify config, only enable tree shaking related options by default.
> feat: add default minify config

- e2e/README.md
- e2e/cases/entry/glob/package.json
- e2e/cases/entry/glob/rslib.config.ts
- e2e/cases/entry/glob/src/bar.ts
- e2e/cases/entry/glob/src/foo.ts
- e2e/cases/entry/glob/src/ignore/baz.ignore.ts
- e2e/cases/entry/glob/src/index.ignore.ts
- e2e/cases/entry/glob/src/index.ts
- e2e/cases/entry/index.test.ts
- e2e/cases/entry/multiple/package.json
- e2e/cases/entry/multiple/rslib.config.ts
- e2e/cases/entry/multiple/src/bar.ts
- e2e/cases/entry/multiple/src/foo.ts
- e2e/cases/entry/multiple/src/index.ts
- e2e/cases/entry/single/package.json
- e2e/cases/entry/single/rslib.config.ts
- e2e/cases/entry/single/src/foo.ts
- e2e/cases/entry/single/src/index.ts
- pnpm-lock.yaml
add entry tests to align with tests of Modern.js Module `input` config
> test: add entry tests

- e2e/README.md
- e2e/cases/copy/index.test.ts
- e2e/cases/copy/package.json
- e2e/cases/copy/rslib.config.ts
- e2e/scripts/shared.ts
- pnpm-lock.yaml
> test: add copy tests

- e2e/package.json
- examples/react-component/package.json
- packages/core/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
bump rsbuild 1.0.1-rc.0
https://github.com/web-infra-dev/rsbuild/releases/tag/v1.0.1-rc.0
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0
> chore: bump rsbuild 1.0.1-rc.0

- .changeset/old-ducks-invent.md
- CONTRIBUTING.md
- e2e/cases/alias/__snapshots__/index.test.ts.snap
- e2e/cases/auto-extension/index.test.ts
- e2e/cases/extension-alias/__snapshots__/index.test.ts.snap
- e2e/cases/minify/index.test.ts
- e2e/cases/resolve/index.test.ts
- e2e/cases/syntax/__snapshots__/index.test.ts.snap
- package.json
- pnpm-lock.yaml
waiting for SWC bump to fix issue of `CONCATENATED MODULE` being removed.
> chore: do not override rspack

- .changeset/config.json
> chore: changeset fixed add create-rslib

- packages/create-rslib/bin.js
- packages/create-rslib/package.json
- packages/create-rslib/src/index.ts
Fix broken shebang line in bin file:
https://github.com/web-infra-dev/rslib/issues/166
> fix(create-rslib): broken shebang line in bin file

- e2e/cases/minify/config/package.json
- e2e/cases/minify/config/rslib.config.ts
- e2e/cases/minify/config/src/index.ts
- packages/core/src/config.ts
- packages/core/tests/config.test.ts
- pnpm-lock.yaml
Use the minify option when user provided and stop merging the default options. If not provided, use the default options.
> fix: could accept minify from user

- CONTRIBUTING.md
- e2e/package.json
- examples/react-component/package.json
- package.json
- packages/core/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
bump rsbuild 1.0.1-rc.3
rspack 1.0.1
> chore: bump rsbuild 1.0.1-rc.3

- CONTRIBUTING.md
- e2e/package.json
- examples/react-component/package.json
- packages/core/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- vitest.workspace.ts
update rsbuild 1.0.1-rc.4
rspack 1.0.3
> chore: update rsbuild 1.0.1-rc.4

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
> chore: bump rslib 0.0.5

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
> chore: bump Rslib 0.0.6

- CONTRIBUTING.md
- e2e/cases/external-helpers/__snapshots__/index.test.ts.snap
- e2e/cases/resolve/index.test.ts
- package.json
- pnpm-lock.yaml
Bump to prevent the rspack ecosystem CI from failing.
> chore: bump @rspack/core to canary

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
> chore: bump Rslib 0.0.7

- packages/plugin-dts/rslib.config.ts
> chore: use syntax in rslib.config.ts

- .changeset/strong-geese-sing.md
> chore: add changeset

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
> chore: bump Rslib 0.0.8

- pnpm-lock.yaml
- scripts/dictionary.txt
- website/package.json
- website/rspress.config.ts
Setup Google Analytics for Rslib website.
> docs: setup Google Analytics

- CONTRIBUTING.md
- package.json
- packages/core/src/config.ts
- packages/core/tests/__snapshots__/config.test.ts.snap
- pnpm-lock.yaml
- tests/integration/decorators/__snapshots__/index.test.ts.snap
- tests/integration/require/import-dynamic/index.ts
- tests/integration/require/import-dynamic/package.json
- tests/integration/require/import-dynamic/rslib.config.ts
- tests/integration/require/index.test.ts
- tests/integration/require/require-as-expression/index.js
- tests/integration/require/require-as-expression/package.json
- tests/integration/require/require-as-expression/rslib.config.ts
- tests/integration/require/require-dynamic/index.ts
- tests/integration/require/require-dynamic/package.json
- tests/integration/require/require-dynamic/rslib.config.ts
- tests/integration/require/require-resolve/index.ts
- tests/integration/require/require-resolve/package.json
- tests/integration/require/require-resolve/rslib.config.ts
Fix https://github.com/web-infra-dev/rslib/issues/204.
> fix: preserve require.resolve / dynamic require / dynamic import

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
> chore: bump Rslib 0.0.9

- .github/workflows/test-ubuntu.yml
> chore: fix ci name typo

- .changeset/proud-sheep-end.md
- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
> Release v0.0.12

- website/docs/en/guide/advanced/module-federation.mdx
- website/docs/zh/guide/advanced/module-federation.mdx
The runtime code in `@module-federation/enhanced` should be bundled into the output.
> docs: change enhanced to dev dep

- tests/benchmark/index.bench.ts
chore(infra/bench): remove getCwdByExample stack in bench
> chore(infra/bench): remove getCwdByExample stack in bench

- website/docs/en/config/rsbuild.mdx
- website/docs/en/guide/basic/cli.mdx
- website/docs/en/guide/basic/configure-rslib.mdx
> docs: configure Rslib

- packages/core/package.json
- packages/core/rslib.config.ts
- packages/create-rslib/package.json
- packages/create-rslib/rslib.config.ts
- packages/plugin-dts/package.json
- packages/plugin-dts/rslib.config.ts
- pnpm-lock.yaml
> chore: bump Rslib 0.0.17

- examples/module-federation/mf-react-component/package.json
- pnpm-lock.yaml
> chore: update dep version of storybook

- package.json
do not build website when install dependencies
> chore: do not build website when install dependencies

- packages/create-rslib/bin.js
- packages/create-rslib/package.json
- packages/create-rslib/src/index.ts
Remove the workaround introduced in https://github.com/web-infra-dev/rslib/issues/166.
> chore(create-rslib): remove shebang workaround

- website/docs/en/config/lib/redirect.mdx
- website/docs/en/config/lib/syntax.mdx
Correct syntax and redirect examples.
> docs: correct syntax and redirect examples

- pnpm-lock.yaml
- website/package.json
Fix website broken by React 19:
https://github.com/web-infra-dev/rspress/releases/tag/v1.38.0
> docs: fix website broken by React 19

- .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
- .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
> Issues types allow you to classify and manage your issues with a shared and consistent language across all repositories in the organization, such as bugs or tasks.
https://github.com/orgs/community/discussions/139933
> chore(workflow): set Issue types

- website/docs/zh/guide/advanced/storybook.mdx
> fix: zh docs links

- website/docs/en/config/lib/external-helpers.mdx
- website/docs/en/config/lib/syntax.mdx
- website/docs/zh/config/lib/external-helpers.mdx
- website/docs/zh/config/lib/syntax.mdx
> docs: correct config position level

- packages/core/package.json
- packages/core/rslib.config.ts
- packages/create-rslib/package.json
- packages/create-rslib/rslib.config.ts
- packages/plugin-dts/package.json
- packages/plugin-dts/rslib.config.ts
- packages/plugin-dts/src/index.ts
- pnpm-lock.yaml
- scripts/dictionary.txt
Twink repository URL as ref of https://publint.dev/@rslib/core@0.1.4.
> build: add rsbuild-plugin-publint

- .github/workflows/benchmark.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
> chore(CI): run benchmark daily and manually

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
> Release v0.2.2

- packages/core/src/types/config.ts
- packages/plugin-dts/README.md
- website/docs/en/config/lib/dts.mdx
- website/docs/en/config/lib/redirect.mdx
- website/docs/en/config/lib/shims.mdx
- website/docs/zh/config/lib/dts.mdx
- website/docs/zh/config/lib/redirect.mdx
- website/docs/zh/config/lib/shims.mdx
add jsDoc for more configurations
close: #350
> chore: add jsDoc for more configurations

- package.json
> chore(deps): bump pnpm v10

- .vscode/extensions.json
- .vscode/settings.json
- biome.json
- add VSCode recommendations
- use prettier to format mdx/md files by default
> chore(infra): add VSCode recommendations

- packages/core/src/constant.ts
- packages/core/tests/constant.test.ts
> fix: edge case of dts RegExp

- tests/integration/redirect/style.test.ts
- tests/integration/redirect/style/rslib.config.ts
- tests/integration/redirect/style/src/pkg/index.ts
close https://github.com/web-infra-dev/rslib/issues/617
> test(redirect): add 3rd packages css test

- pnpm-lock.yaml
- tests/integration/style/tailwindcss/bundle-false/package.json
- tests/integration/style/tailwindcss/bundle-false/postcss.config.ts
- tests/integration/style/tailwindcss/bundle-false/rslib.config.ts
- tests/integration/style/tailwindcss/bundle-false/src/index.css
- tests/integration/style/tailwindcss/bundle-false/src/index.ts
- tests/integration/style/tailwindcss/bundle-false/tailwind.config.cjs
- tests/integration/style/tailwindcss/index.test.ts
test: add tailwindcss bundle false test case
https://modernjs.dev/module-tools/guide/best-practices/use-tailwindcss.html
> test: add tailwindcss bundle false test case

- website/docs/en/guide/solution/nodejs.mdx
- website/docs/en/guide/start/quick-start.mdx
patch of https://github.com/web-infra-dev/rslib/pull/721
> docs: patch necessary changes

- package.json
update pnpm 10.2.0
- https://github.com/pnpm/pnpm/releases/tag/v10.2.0
- https://github.com/pnpm/pnpm/issues/8978
> chore(deps): update pnpm 10.2.0

- pnpm-lock.yaml
- website/package.json
- website/rspress.config.ts
https://github.com/web-infra-dev/rspress/pull/1797
https://github.com/web-infra-dev/rspress/releases/tag/v1.41.0
> docs: update rspress 1.41.0 and enable codeBlocks search

- website/docs/en/config/lib/bundle.mdx
- website/docs/en/guide/basic/output-structure.mdx
- website/docs/zh/config/lib/bundle.mdx
- website/docs/zh/config/lib/syntax.mdx
- website/docs/zh/guide/basic/output-structure.mdx
docs: add bundleless mode img and polish the some words
`参见` -> `参考`
https://github.com/rspack-contrib/rstack-design-resources/pull/23
> docs: add bundleless mode img and polish the some words

- packages/plugin-dts/src/utils.ts
fix: windows issue in dts redirect
> fix: windows issue in dts redirect

- pnpm-lock.yaml
- website/package.json
- website/theme/components/Hero.tsx
Display GitHub button on homepage:
> docs: display GitHub button on homepage

- packages/plugin-dts/README.md
- website/docs/en/config/lib/redirect.mdx
- website/docs/zh/config/lib/redirect.mdx
modify examples of `redirect.dts.extension`
> docs: modify examples of `redirect.dts.extension`

- tests/integration/cli/build-watch/build.test.ts
> test: correct build watch test

- packages/core/src/asset/assetConfig.ts
- packages/plugin-dts/src/dts.ts
- tests/integration/style/less/bundle-false/rslib.config.ts
- website/docs/en/guide/solution/react.mdx
- website/docs/zh/guide/solution/react.mdx
- add SVGR in React solution
- remove some comments of TODO
> docs: add SVGR in React solution

- examples/module-federation/mf-host/package.json
- examples/module-federation/mf-remote/package.json
- packages/core/package.json
- packages/create-rslib/fragments/tools/storybook-react-js/package.json
- packages/create-rslib/fragments/tools/storybook-react-ts/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[react]-[storybook]-js/package.json
- packages/create-rslib/template-[react]-[storybook]-ts/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- tests/package.json
- website/package.json
https://github.com/web-infra-dev/rsbuild/releases/tag/v1.2.13
> chore(deps): update @rsbuild/core 1.2.13

- website/docs/zh/guide/start/quick-start.mdx
Remove duplicate text
https://lib.rsbuild.dev/zh/guide/start/quick-start
> docs: fix typo

- examples/module-federation/mf-host/package.json
- examples/module-federation/mf-remote/package.json
- packages/core/package.json
- packages/create-rslib/fragments/tools/storybook-react-js/package.json
- packages/create-rslib/fragments/tools/storybook-react-ts/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[react]-[storybook]-js/package.json
- packages/create-rslib/template-[react]-[storybook]-ts/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- tests/integration/asset/__snapshots__/index.test.ts.snap
- tests/integration/auto-extension/index.test.ts
- tests/integration/bundle-false/__snapshots__/index.test.ts.snap
- tests/integration/minify/index.test.ts
- tests/package.json
- website/package.json
Update @rsbuild/core to v1.2.18 and fix failed snapshots.
https://github.com/web-infra-dev/rsbuild/releases
> chore(deps): update @rsbuild/core to v1.2.18 and fix snapshots

- packages/plugin-dts/src/index.ts
fix(dts): add missing `optionalDependencies` type
> fix(dts): add missing `optionalDependencies` type

- packages/core/src/plugins/EntryChunkPlugin.ts
Remove TODO as https://github.com/web-infra-dev/rspack/pull/9782 landed.
> refactor: use sync hook of `afterCompile`

- pnpm-lock.yaml
- website/package.json
rollback rspress to 2.0.0-alpha.8
> chore(deps): rollback rspress to 2.0.0-alpha.8

- examples/module-federation/mf-host/package.json
- examples/module-federation/mf-remote/package.json
- packages/core/package.json
- packages/create-rslib/fragments/tools/storybook-react-js/package.json
- packages/create-rslib/fragments/tools/storybook-react-ts/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[react]-[storybook]-js/package.json
- packages/create-rslib/template-[react]-[storybook]-ts/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- tests/package.json
- website/package.json
bump Rsbuild 1.3.7 which based on an Rspack version that have changes about resolver.
fix: #897
> chore(deps): update Rsbuild 1.3.7

- packages/plugin-dts/src/apiExtractor.ts
Instructive error message.
before: 
after:
> fix(dts): explicit error for @microsoft/api-extractor is required

- website/docs/zh/config/rsbuild/output.mdx
> docs: fix output.assetPrefix badge typo

- tests/integration/style/style-inject/index.test.ts
- website/docs/en/config/rsbuild/output.mdx
- website/docs/zh/config/rsbuild/output.mdx
add `output.injectStyles` docs.
> docs: output.injectStyles

- packages/create-rslib/fragments/tools/storybook-react-js/package.json
- packages/create-rslib/fragments/tools/storybook-react-ts/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[react]-[storybook]-js/package.json
- packages/create-rslib/template-[react]-[storybook]-ts/package.json
Should not pin Rsbuild version of Storybook.
> fix(create-rslib): do not pin Rsbuild version

- pnpm-lock.yaml
- website/package.json
- website/rspress.config.ts
Add OG images for website:
- Default: https://assets.rspack.dev/rslib/rslib-og-image.png
- For the introducing blog: https://assets.rspack.dev/rslib/assets/rslib-og-image-introducing.png
> docs: add OG images for website

- .github/renovate.json5
see https://github.com/web-infra-dev/rslib/pull/992
> chore(renovate): ignore updating `@ast-grep/napi`

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
https://github.com/web-infra-dev/rslib/releases/tag/v0.10.0
> chore(deps): bump Rslib v0.10.0

- packages/plugin-dts/src/tsc.ts
Should emit all kinds of diagnostics when composite is true
> fix(dts): should emit all kinds of diagnostics when composite is true

- examples/module-federation/mf-host/package.json
- examples/module-federation/mf-remote/package.json
- packages/core/package.json
- packages/create-rslib/fragments/tools/storybook-react-js/package.json
- packages/create-rslib/fragments/tools/storybook-react-ts/package.json
- packages/create-rslib/fragments/tools/storybook-vue-js/package.json
- packages/create-rslib/fragments/tools/storybook-vue-ts/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[react]-[storybook]-js/package.json
- packages/create-rslib/template-[react]-[storybook]-ts/package.json
- packages/create-rslib/template-[vue]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[vue]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[vue]-[storybook]-js/package.json
- packages/create-rslib/template-[vue]-[storybook]-ts/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- tests/package.json
- website/package.json
bump Rsbuild 1.4.0
https://rspack.dev/blog/announcing-1-4
> chore(deps): bump Rsbuild 1.4.0

- .vscode/settings.json
- biome.json
- package.json
- pnpm-workspace.yaml
- scripts/dictionary.txt
Moving settings to `pnpm-workspace.yaml`
https://github.com/orgs/pnpm/discussions/9037
> chore(pnpm): bump pnpm and move settings to `pnpm-workspace.yaml`

- README.md
- README.zh-CN.md
Add a badge to deepwiki in the repo's README file to auto-refresh the wiki weekly.
> docs: add deepwiki badge

- packages/plugin-dts/src/tsc.ts
Align with `tsc` behaviour, see https://github.com/microsoft/TypeScript/blob/65cb4bd2d52cd882f2c3a503681479eb2ed291ca/src/compiler/watch.ts#L576-L611
> fix(dts): get pre-emit diagnostics before emit

- biome.json
- pnpm-lock.yaml
former PR does not rebase main so the ci passed but the main lint ci failed.
> chore: fix pnpm dedupe

- examples/module-federation/mf-host/package.json
- examples/module-federation/mf-remote/package.json
- package.json
- packages/core/package.json
- packages/create-rslib/fragments/tools/storybook-react-js/package.json
- packages/create-rslib/fragments/tools/storybook-react-ts/package.json
- packages/create-rslib/fragments/tools/storybook-vue-js/package.json
- packages/create-rslib/fragments/tools/storybook-vue-ts/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[react]-[storybook]-js/package.json
- packages/create-rslib/template-[react]-[storybook]-ts/package.json
- packages/create-rslib/template-[vue]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[vue]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[vue]-[storybook]-js/package.json
- packages/create-rslib/template-[vue]-[storybook]-ts/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- tests/package.json
- website/package.json
bump Rsbuild 1.4.10 and Rstest 0.0.10
- https://github.com/web-infra-dev/rsbuild/releases/tag/v1.4.10
- https://github.com/web-infra-dev/rstest/releases/tag/v0.0.10
> chore(deps): bump Rsbuild 1.4.10 and Rstest 0.0.10

- packages/plugin-dts/src/apiExtractor.ts
- packages/plugin-dts/src/dts.ts
do not block dts watch of tsc when bundle dts failed
> fix(dts): should keep watch if bundle dts failed

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
> chore(deps): bump Rslib v0.12

- website/docs/en/guide/migration/modernjs-module.mdx
- website/docs/zh/guide/migration/modernjs-module.mdx
remove unnecessary paragraphs in modernjs-module migration docs
> docs: remove unnecessary paragraphs in modernjs-module migration docs

- examples/module-federation/mf-host/package.json
- examples/module-federation/mf-remote/package.json
- packages/core/package.json
- packages/create-rslib/fragments/tools/storybook-react-js/package.json
- packages/create-rslib/fragments/tools/storybook-react-ts/package.json
- packages/create-rslib/fragments/tools/storybook-vue-js/package.json
- packages/create-rslib/fragments/tools/storybook-vue-ts/package.json
- packages/create-rslib/template-[react]-[rstest,storybook]-js/package.json
- packages/create-rslib/template-[react]-[rstest,storybook]-ts/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[react]-[storybook]-js/package.json
- packages/create-rslib/template-[react]-[storybook]-ts/package.json
- packages/create-rslib/template-[vue]-[rstest,storybook]-js/package.json
- packages/create-rslib/template-[vue]-[rstest,storybook]-ts/package.json
- packages/create-rslib/template-[vue]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[vue]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[vue]-[storybook]-js/package.json
- packages/create-rslib/template-[vue]-[storybook]-ts/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- tests/integration/node-polyfill/bundle-false/package.json
- tests/integration/node-polyfill/bundle/package.json
- tests/package.json
- website/package.json
bump Rsbuild 1.5.0-rc.0
https://github.com/web-infra-dev/rsbuild/releases/tag/v1.5.0-rc.0
> chore(deps): bump Rsbuild 1.5.0-rc.0

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
See https://github.com/web-infra-dev/rslib/releases/tag/v0.13.0
> Release v0.13.0

- examples/module-federation/mf-host/package.json
- examples/module-federation/mf-remote/package.json
- packages/core/package.json
- packages/create-rslib/fragments/tools/storybook-react-js/package.json
- packages/create-rslib/fragments/tools/storybook-react-ts/package.json
- packages/create-rslib/fragments/tools/storybook-vue-js/package.json
- packages/create-rslib/fragments/tools/storybook-vue-ts/package.json
- packages/create-rslib/template-[react]-[rstest,storybook]-js/package.json
- packages/create-rslib/template-[react]-[rstest,storybook]-ts/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[react]-[storybook]-js/package.json
- packages/create-rslib/template-[react]-[storybook]-ts/package.json
- packages/create-rslib/template-[vue]-[rstest,storybook]-js/package.json
- packages/create-rslib/template-[vue]-[rstest,storybook]-ts/package.json
- packages/create-rslib/template-[vue]-[storybook,vitest]-js/package.json
- packages/create-rslib/template-[vue]-[storybook,vitest]-ts/package.json
- packages/create-rslib/template-[vue]-[storybook]-js/package.json
- packages/create-rslib/template-[vue]-[storybook]-ts/package.json
- packages/plugin-dts/package.json
- pnpm-lock.yaml
- tests/integration/node-polyfill/bundle-false/package.json
- tests/integration/node-polyfill/bundle/package.json
- tests/package.json
- website/package.json
bump Rsbuild 1.5.5
close: #1204 
https://github.com/web-infra-dev/rsbuild/releases/tag/v1.5.5
> chore(deps): bump Rsbuild 1.5.5

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
https://github.com/web-infra-dev/rslib/releases/tag/v0.13.1
> Release v0.13.1

- packages/core/package.json
- packages/create-rslib/package.json
- packages/plugin-dts/package.json
https://github.com/web-infra-dev/rslib/releases/tag/v0.13.3
> Release v0.13.3
